### ISSUE TITLE
Twitter Search API implementation

### ISSUE THREAD

**Issue by acegreen** [mattdonnelly/Swifter#100]
Hello,

First off great repo. I was wondering if you can this framework to get data of the Twitter search API. For example all tweets for stock symbol $AAPL

I only see methods for grabbing timeline and using stream API, is there one for a search API?

Thanks in advance
Ace

**Comment by mattdonnelly** [comment]
Hi there, think this might be what you're looking for: https://dev.twitter.com/streaming/reference/post/statuses/filter
