### ISSUE TITLE
getting geolocation on the bases of tweets

### ISSUE THREAD

**Issue by RYG81** [mattdonnelly/Swifter#111]
Hi is it possible to get geo loation on the bases of tweets?
Rahul

**Comment by zntfdr** [comment]
Hi @RYG81 
there's an optional "coordinates" field among the returned Tweet fields. 

You can read more about it here: https://dev.twitter.com/overview/api/tweets#obj-coordinates .

**Comment by RYG81** [comment]
Ok.
I have one more problem, my project is in Xcode 6.4 and swift 1.2, is it possible to get swifter for that?
Updating my project to xcode7 and swift 2 is near to impossible for me.

**Comment by zntfdr** [comment]
Absolutely, yes!

You just need to pull the current Swifter repository on your machine and undo the last git commit (last commit updates Swifter to Swift 2.0).

**Comment by RYG81** [comment]
Not able to get coordinates, any example project available here, using swifter?

**Comment by zntfdr** [comment]
Dear @RYG81 ,
From the [link](https://dev.twitter.com/overview/api/tweets) I sent you above
> ###### coordinates 
> Nullable. Represents the geographic location of this Tweet as reported by the user or client application. The inner coordinates array is formatted as geoJSON (longitude first, then latitude).

They key is **Nullable**: 
From my experience, most of the Tweets don't include the coordinates field. 

Working/Tested example:
let's assume you tweet JSON data, `[String: JSONValue]`, is named tweetData, just put this code where you read any other Tweet field:
````swift
        let coordinates: [Double]?
        
        if let geoJSON = tweetData["coordinates"]?.object,
            let coordinatesJSON = geoJSON["coordinates"]?.array {
            coordinates = coordinatesJSON.map { $0.double! }
        } else {
            coordinates = nil
        }
````
Cheers!

**Comment by RYG81** [comment]
OK
