### ISSUE TITLE
Twitter Login Button

### ISSUE THREAD

**Issue by mhatzitaskos** [mattdonnelly/Swifter#113]
There is no way to implement the twitter login button with swifter. Only way to login to twitter is if the device user has already connected through the device settings.
There should be a way to implement a twitter login button so that if the user has not logged in through the device settings, he can do so using the button.

**Comment by zntfdr** [comment]
This library is the back-end of your app: It deals with the Twitter API for you. 

How the user interacts with your app is up to you.

Swifter allows different kind of user/app authentication: via "device settings" like you said, via OAuth Tokens and maybe more (I can't check the code now).

If you want to use something easier to implement, you should check the [official Twitter library](https://get.fabric.io/).

**Comment by mhatzitaskos** [comment]
hello zntfdr, and thanks for the prompt reply.
Swifter is really great and simple at dealing with the twitter API and I have already used it to create an app that I wanted. What I am missing is how I can create a login button through my app. 

I tried to integrate the official twitter library and using the login credentials from that and use it in swifter but I have not been successful yet. If you have any ideas to present as to how to integrate swifter with an in app login button I would be very interested in them.

**Comment by zntfdr** [comment]
I don't have an example to give you, but I'm sure you can find something online.

Regarding the implementation of both libraries: don't. They're not built to cooperate together. 

If I may, I suggest you to focus on just one library, study how it works and you'll be super happy with the results.

Cheers!
