### ISSUE TITLE
Persist user accounts after login

### ISSUE THREAD

**Issue by xcodewarrier** [mattdonnelly/Swifter#115]
Given the following from the example code:

    let accountStore = ACAccountStore()
    let accountType = accountStore.accountTypeWithAccountTypeIdentifier(ACAccountTypeIdentifierTwitter)
     accountStore.requestAccessToAccountsWithType(accountType, options: nil) {
                 granted, error in
          if granted {
            let twitterAccounts = accountStore.accountsWithAccountType(accountType)
            let twitterAccount = twitterAccounts[0] as! ACAccount
            self.delegate?.swifter = Swifter(account: twitterAccount)

How do I then save this account so I don't have to keep asking the user permission to access their account?

**Comment by zntfdr** [comment]
Hi @xcodewarrier ,
your app can request such permission only once (Apple rules).

The next time you run the app on the same device, it won't request the user permission again: the permission was granted (or not) the first time it was asked.

When the app runs this code for the second (or third, or fouth...) time, this code just makes sure that the app has the permission to access to the device Twitter Accounts and it retrieves the current (first) Twitter account linked to the device.

Cheers!
