### ISSUE TITLE
Move from NSURLConnection to NSURLSession

### ISSUE THREAD

**Issue by zntfdr** [mattdonnelly/Swifter#119]
As of iOS 9.0, NSURLConnection is deprecated. 

![1 pic](https://cloud.githubusercontent.com/assets/5277837/12072977/92869990-b13d-11e5-84fb-ae40fcb3ae61.jpg)

![2 pic](https://cloud.githubusercontent.com/assets/5277837/12072980/e3d346d6-b13d-11e5-8eaf-c5f841dd6b53.jpg)

**Comment by meteochu** [comment]
Basically finished the conversion from NSURLConnection to NSURLSession in #131 (Does require testing though)
