### ISSUE TITLE
Problem with tweet posting

### ISSUE THREAD

**Issue by orkhanalizade** [mattdonnelly/Swifter#122]
Hi. I'm trying to send tweet after the success log in process, but it doesn't publish tweet. This is my code:

    let url = NSURL(string: "DrinkMe://success")!
                swifter.authorizeWithCallbackURL(url, success: { (accessToken, response) -> Void in
                    }, failure: { (error) -> Void in
                        self.alertWithTitle("Error", message: error.localizedDescription)
                    }, openQueryURL: { (url) -> Void in
                        if #available(iOS 9.0, *) {
                            let webView = SFSafariViewController(URL: url)
                            webView.delegate = self
                            self.presentViewController(webView, animated: true, completion: nil)
                            print("1")
                        } else {
                            // Fallback on earlier versions
                            UIApplication.sharedApplication().openURL(url)
                            print("2")
                        }
                    }, closeQueryURL: { () -> Void in
                        self.swifter.postStatusUpdate("Hello, world", success: {
                            (status: Dictionary<String, JSONValue>?) in
                            }, failure: {
                                (error: NSError) in
                        })
                       self.presentedViewController?.dismissViewControllerAnimated(true, completion: nil)
                })
            }

in `closeQueryURL` I'm trying to post my tweet, but it doesn't publish anything. What is the problem?

**Comment by alexdd55** [comment]
do a print on the stats and on the error. this will show you what the problem is... something should comeback from the API either an error emssage or the postet status

**Comment by orkhanalizade** [comment]
@alexdd55 it prints `Your credentials do not allow access to this resource` but in my app settings I set my permissions to `Read and Write`. So, why it cannot access?

**Comment by orkhanalizade** [comment]
Oh, it works! Thanks!
