### ISSUE TITLE
Repository Maintenance: call for contributors?

### ISSUE THREAD

**Issue by zntfdr** [mattdonnelly/Swifter#124]
@mattdonnelly has been obviously busy in the past few months.

This made the repo development suffer quite a bit.

I honestly believe Swifter is an amazing framework and it would be a pity to see it die because of the lack of engagement of the repo owner. 

I'd like to propose a solution:
much like https://github.com/danielgindi/ios-charts , I propose that @mattdonnelly elects some [Swifter collaborators](https://help.github.com/articles/adding-collaborators-to-a-personal-repository/), which are contributors enabled to manage the repo almost like if it was theirs (closing issues, merging pull requests and the likes) in order to have a better/faster Swifter development.

I'd say @meteochu is the most suitable for this position, but I leave to @mattdonnelly the final decision on the matter.

Please, feel free to share any thoughts on the issue.

**Comment by mattdonnelly** [comment]
This is a great idea and something I've been meaning to organise myself for a while now but just haven't found the time. It would be great to see this project more actively developed than it is currently. If anyone is interested in being added as a collaborator please let me know.

In the meantime, I agree that @meteochu would be a great candidate, so if you're interested @meteochu, let me know and I'd be happy to add you.

I'd also be happy to you @zntfdr, if you'd like. You've made a bunch PRs lately and have been great at replying to open issues.

**Comment by zntfdr** [comment]
Thanks for the prompt reply!

I tried to contact @meteochu on Twitter a few days ago with no avail, let's see if we have more luck in here.

I was not expecting to be considered as a candidate: I would be more than happy to be a Swifter collaborator :)

Can we expect to see you more active in the upcoming months? 
I believe that the shift from NSURLConnection to NSURLSession is going to take  time and it would be much better if it could be handled with your help.

**Comment by mattdonnelly** [comment]
Great, I'll add you as a collaborator now. Hopefully @meteochu will get back to us soon.

I'd like to be as involved as I can, but will have limited time unfortunately. I think you're right about it taking a good bit of time to switch to NSURLSession but it will be time well spent.

**Comment by zntfdr** [comment]
Awesome, thanks!

For the NSURLSession shift I believe the best thing to do is plan ahead, open a new branch and, once it's all done, merge it to the master.

I'll try to get involved as much as possible: 
first thing I would like to take care of is polishing the repository both from old code and open issues.

Thanks again!
Cheers

**Comment by meteochu** [comment]
Wow, I'm honoured. Sorry @zntfdr, I thought I replied to that DM you sent me a while ago, seems like I need to fix the DM functions in my Twitter client. 😂

As for Swifter, honestly, the project got a bit too complex and out of hands after I migrated it to Swift 2.0 (and added support for iOS 9) that I ended up rewriting my own Twitter framework that hooks right into my project. Also, rather than using NSURLSession or NSURLConnection, I'm using Alamofire to do all the networking which simplifies things a lot more. I'm definitely happy to help organize this project, and see if I can merge the things I added into my project back into Swifter. 

For example, rather than having... 
`swifter.getStatusesLookupTweetIDs(...) { }`
I'm using something like...
`Tweet.lookup(usingTweetIDs: [String], credential, ...) { }`

**Comment by zntfdr** [comment]
[@Erica](https://github.com/erica) just [ran quick a survey](http://ericasadun.com/2016/02/12/survey-results-labels/) on the matter after expressing her doubts in this [blog post](http://ericasadun.com/2016/02/09/the-trouble-with-argument-labels-some-thoughts/).

[From the survey results](http://ericasadun.com/2016/02/12/survey-results-labels/), and also in my opinion, the way you used the argument labels looks nicer and cleaner than using the old Objective-C style way :)

**Comment by meteochu** [comment]
Definitely. I'm doing everything with Alamofire, so I can confirm that streaming works with Alamofire.

Although, this is just in my project alone. For a standalone framework like Swifter, it's probably best to use NSURLSession (unless @mattdonnelly thinks using Alamofire is more beneficial)

**Comment by zntfdr** [comment]
Yes, my question was just out of curiosity: I agree that Swifter has to stay a standalone framework.

**Comment by lewis-smith** [comment]
Hey all. I'd like to get involved in helping with Swifter. Not looking to be an admin or anything, but hopefully can help out with some PRs. Anyway, just wanted to say hi and I look forward to helping out. I think a great start would be clearing out the issues list, a lot of them can be closed and it makes finding something to do tricky. 

I'm also interested in adding tests , maybe this something that I can start on right away as it might help with the transitions discussed above.

**Comment by zntfdr** [comment]
Hi @lewis-smith, 
I really like how this thread turned out: I'm pretty sure we can take Swifter back on track!

I'll be more than happy to start cleaning old open issues.

Tests are absolutely on the bucket list: it would be great to have a [Travis CI integration](https://travis-ci.org/) :)

**Comment by mattdonnelly** [comment]
Tests and CI would be a really great addition +1

**Comment by mattdonnelly** [comment]
Also, in response to @meteochu points about naming. I think updating the naming scheme to be more Swift-y is a great idea, but I think we should try to keep the names close to the names in twitter's API docs

**Comment by lewis-smith** [comment]
Hi @zntdfr 

Good work on the purging of the issues, going to be much better to work with :)

Tests is my too priority, but I'd like to do CI too at some point. 

Thanks for the friendly welcome too :)

**Comment by meteochu** [comment]
@mattdonnelly Yeah, it's definitely possible to keep the naming similar to the Twitter API docs by using the correct keywords. `.lookup(id:)` etc while making it Swift-ier! 

Also, I'm definitely down to become a collaborator for the project if it's still open. :stuck_out_tongue:

**Comment by zntfdr** [comment]
@meteochu using again Swifter in your app without overhauling your codebase (or Swifter's) can be done by applying the same concept as Swift's Convenience Initializers [1] via one Swifter extension: 
`````swift
extension Swifter {
  func lookup(usingTweetIDs: [String], credential, ...) { // this is the func name in your app codebase        
    getStatusesLookupTweetIDs(...) // this is Swifter's
  }
  // add here more functions that you use
}
`````

If there's a real need, then we can obviously change all the naming in the repo, but this would break  *every*  project that has been using Swifter until now :scream: 

Also, I agree with @mattdonnelly that we should stay coherent as much as possible with Twitter's API documentation.

[1] see "Designated Initializers and Convenience Initializers" chapter [here](https://developer.apple.com/library/mac/documentation/Swift/Conceptual/Swift_Programming_Language/Initialization.html).

PS
If we really want to do the renaming thingy, then we could use the same concept presented above for a couple of Swifter versions, on which both new and old naming will work, and later pull the plug on the old naming.
During this shift phase we would put an alert in the main readme and in the Swifter release notes about these changes asking the developers to move their code to the new naming style.

I honestly believe we should give priority to something else first (`*cough*` #119 `*cough*`) ;)

**Comment by zntfdr** [comment]
@lewis-smith any contribution will be much appreciated: be it a suggestion, tests, CI or else! :) 
Thank you

**Comment by zntfdr** [comment]
I believe we're good now :+1: 

Thanks everybody for the fantastic response!
