### ISSUE TITLE
Mac Demo fails due to use of UIViewController parameter

### ISSUE THREAD

**Issue by SAPIENTechnologies** [mattdonnelly/Swifter#125]
Cannot build SwifterMac because of the UIViewController parameter in the authorizeWithCallbackURL func in SwifterAuth.swift giving the error "Use of undeclared type 'UIViewController".

**Comment by zntfdr** [comment]
Thanks!

Even if I were to revert c9542d21ac15d441a0cc4a1970dce78cbcdfd1c2 I see that there are still other errors due to old code (println instead of print, authorizeAppOnlyWithSuccess call with a parameter missing). I'll review the code in a few hours (5am here)

**Comment by meteochu** [comment]
Yeah... I completely forgot about Mac when I was implementing that. I'll figure something out when I can touch the code directly. Most likely, I'll either split it into 2 methods (1 with `#if os(iOS)`), or just rewrite it completely to work nicer with everything else.

**Comment by zntfdr** [comment]
Thank you @meteochu :)

The code was not compiling prior to your pull request:
it just happen that @SAPIENTechnologies spotted the problem now :+1:

**Comment by meteochu** [comment]
Fixed it in #129, so this can be closed as soon as that's merged.
