### ISSUE TITLE
Login can not return the app

### ISSUE THREAD

**Issue by flamme0011** [mattdonnelly/Swifter#130]
Hi
I copy your swifter classes and added my project. (Also login codes are same too)
When I click the login twitter button I can login but can not return the app.

It says redirecting you back to the application. This may take a few moments but it did not do anything :((

What is wrong?

**Comment by meteochu** [comment]
Please provide more information. Is this for Swifter iOS or OS X?
For iOS, it should redirect back into the app you launched from (assuming you didn't change with the original login auth code). 
For OS X, the login will succeed, but you just need to go back into the app yourself.

**Comment by flamme0011** [comment]
Hi meteochu
Thanks for your quick reply. 
I fixed my problem. The problem was I forgot to write code in appdelege.
