### ISSUE TITLE
Tweets with Image

### ISSUE THREAD

**Issue by flamme0011** [mattdonnelly/Swifter#134]
I am trying to show user tweets in tableview for iphone app.
Some tweets has image but I can not display them. (I can show text) How can I show it?

PS: I am getting tweet like: 

     var tweetList : [String] = []
        
        let failureHandler: ((NSError) -> Void) = { error in
            self.alertWithTitle("Error", message: error.localizedDescription)
        }
        
        self.swifter.getStatusesUserTimelineWithUserID(userId, count: 5, success: { status in
            
            for item in status!{
                tweetList.append(item["text"].string!)
            }
        
            completionHandler(returnTweets: tweetList)
        
            }, failure: failureHandler)

**Comment by meteochu** [comment]
In your current setup, you're only fetching the and returning the tweet text from the statuses JSON. If you look at the [Twitter API](http://dev.twitter.com) documentation on [Tweet Objects](https://dev.twitter.com/overview/api/tweets), you'll find out that the images are stored in what we call an _entity_ as a URL (ref: [Entities in Objects](https://dev.twitter.com/overview/api/entities-in-twitter-objects))

What you'll need it the _media_ entity fetched from the JSON
```swift
if let urlString = status["entities"]["media"]["media_url_https"].string {
  imageURL = NSURL(string: urlString)!
}
```

After retrieving the URL, you can do the following to get the image:
```swift
let data = NSData(contentsOfURL: imageURL)
let image = UIImage(data: data)
```

On a sidenote, I'd recommend creating storing the tweetList as either an Array of `JSONValue` or create your own `Tweet` wrapper class. Additionally, your code for fetching tweets can be simplified (and improved) using the `CollectionType` method  `.map` :smile: 

```swift
self.swifter.getStatusesUserTimelineWithUserID(userId, count: 5, success: { statuses in
    let tweetList = statuses.map { $0["text"].string! }
    completionHandler(returnTweets: tweetList)
    }, failure: failureHandler) 
```

**Comment by flamme0011** [comment]
Thanks for your help  @meteochu
