### ISSUE TITLE
Upload media

### ISSUE THREAD

**Issue by timothyarmes** [mattdonnelly/Swifter#139]
Hi,

Can I use this library to upload photos/videos? I can't find it, but i'm hoping that I'm just missing the feature...

**Comment by meteochu** [comment]
Swifter does include the methods for uploading media to Twitter. Uploading media can be done like so...
```
swifter.postMedia(imageData, success: { json in
  // returned JSON object contains media info
}, failure: failureHandler)
```

To read more on the requirements for uploading media, I suggest reading through [POST media/upload](https://dev.twitter.com/rest/reference/post/media/upload) on Twitter Developer's Website.

**Comment by timothyarmes** [comment]
Hi,

Yes, I did find that. However that end point is limited to 5 Mb. To send video we need to use the chunked end point variation.

Tim

**Comment by chiragpurohit71085** [comment]
Hi

I want to upload video(I am able to upload image successfully)... I am using following method...(videoData is NSData of video).


 self.swifter.postStatusUpdate("ABcd", media: videoData,success: { (status) -> Void in
            print("Wow image uploadedcd!")
            print(status)
            
            
            }, failure: failureHandler)

I am getting following response.


{"errors":[{"code":189,"message":"Error creating status."}]}

Let me know what I am missing. I also went through 

https://dev.twitter.com/rest/reference/post/media/upload


but I am not getting much idea from there.

Regards,

**Comment by annjawn** [comment]
Is chunked media upload possible in Swifter?

**Comment by rememberit1** [comment]
I'm trying to post a tweet with a photo but every time I try, i get an error "The operation couldn’t be completed. (SwifteriOS.SwifterError error 1.)"

My code looks like

```
var tweetMedia: [String: Any]?
//I then set tweetMedia to a UIImageView from the UIImagePickerControllerOriginalImage
let picForTwitterApi = tweetMedia![UIImagePickerControllerOriginalImage] as! UIImage
let image = UIImagePNGRepresentation(picForTwitterApi) as Data?
self.swifter?.postTweet(status: tweetText, media: image!, inReplyToStatusID: nil, coordinate: nil, placeID: nil, displayCoordinates: nil, trimUser: false, 
tweetMode: TweetMode.default, success: { json in self.alert(title: "Tweet PHOTO sent", message: "👍🏾")
            }, failure: failureHandler)

```
But it does not work, i even tried

```
self.swifter?.postMedia(image!, additionalOwners: nil, success: { json in
                print(json)
```

instead, still no success. When I post a regular vanilla tweet like 
```
self.swifter?.postTweet(status: tweetText, inReplyToStatusID: nil, trimUser: false, tweetMode: TweetMode.default, success: { json in
                print(json).....
```

Everything works perfectly fine, I only have problems when I try to post a photo. Please help. Thanks in advance

**Comment by meteochu** [comment]
#310 adds improvements to uploading media. Closing this issue now.
