### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by srinivasmangipudi** [mattdonnelly/Swifter#14]
I followed your tutorial and added swifter xcode project to my project, but I am getting 151 compilation errors saying - swift compilation error in the SwifteriOS xcode project.

I also tried to build swifteriOS project as it is and get the same compile errors.

**Comment by smhk** [comment]
Here's the current link to add a custom app scheme to an iOS app in an app in Xcode

https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app

For the iOS target, go to "Info" tab and then "URL Types" section.
