### ISSUE TITLE
Cannot return back to the app, after authorizing on safari. 

### ISSUE THREAD

**Issue by pranavkotecha88** [mattdonnelly/Swifter#140]
Hi guys, 
I have copied all the code as it should be from the demo iOS app. The problem is that once it takes me to safari and i authorize the app, it never comes back, it gives me a error saying the url cannot be open and then its stuck there. 

Here is my code:
https://github.com/pranavkotecha88/trendingtweet

**Comment by meteochu** [comment]
Don't forget to add the URL scheme in the **Info.plist** file.
Simply add the following...
```
<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleURLName</key>
        <string>com.mattdonnelly.swifter-scheme</string>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>swifter</string>
        </array>
    </dict>
</array>
```

**Comment by alexdd55** [comment]
+1

**Comment by pranavkotecha88** [comment]
Thank you so much for the help guys :)

**Comment by smhk** [comment]
These days, it's even easier, just click on .........

![screenshot 1](https://user-images.githubusercontent.com/3938526/61723419-ba2c9f00-ad31-11e9-9324-104885a37239.png)
