### ISSUE TITLE
Authentication without safari?

### ISSUE THREAD

**Issue by ht22pt** [mattdonnelly/Swifter#142]
Current version of Swifter only support authentication twitter over safari? I check example and see that. Maybe add this feature to easy custom login multi acc Twitter. With login over safari, it store cookie and can't login 2 account.

**Comment by zntfdr** [comment]
Hi @ht22pt ,
beside the authentication that you see in the examples, you can also "borrow" the Twitter accounts that the user has logged in iOS (the ones that you find in your iPhone Settings/Twitter).

This way you get multiple accounts management for free :)

Please remember that, by using this solution, you have to ask for authorization to access to those accounts (something that Apple lets you do only once), you might do so by writing something like:
`````swift      
let accountStore = ACAccountStore()
let accountType = accountStore.accountTypeWithAccountTypeIdentifier(ACAccountTypeIdentifierTwitter)
    
// Prompt the user for permission to their twitter account stored in the phone's settings
accountStore.requestAccessToAccountsWithType(accountType, options: nil) {
granted, error in
// do something
}
`````

Once the permission is granted, you can initialize Swifter with any of the iPhone's Twitter accounts via simply ``Swifter(account: account)`` (where ``account`` is one of those accounts).

To obtain the accounts list, you might use something like
`````swift
let accounts: [ACAccount] = {
  let twitterAccountType = ACAccountStore().accountTypeWithAccountTypeIdentifier(ACAccountTypeIdentifierTwitter)
  return ACAccountStore().accountsWithAccountType(twitterAccountType) as? [ACAccount]
}()
`````

Please let me know if I can be of any further help!

**Comment by ht22pt** [comment]
Thanks for your answers.
But if my iPhone don't store any Twitter account, I only use login over safari. 
I see Swifter support 2 methods for authentication:
1: over ACAccount store in iPhone settings --> it support many accounts.
2: over WebBrowser by call safari (default browser) for login.

I see on https://github.com/nst/STTwitter, this library can be support login over internal WebClient not use safari. This is a great feature, can internal handle all step working with Twitter rest-api.
Maybe close here?

**Comment by zntfdr** [comment]
Implementing a Twitter Login via in-app WebClient instead of externally via Safari would be nice!
If anybody wants to implement this, please feel free to do it :)

**Comment by meteochu** [comment]
I don't know how I missed this thread, but guess it's better late than never to respond to this.

Swifter utilizes Apple's `SFSafariViewController` to provide login, and it's a web view with everything Safari has, and doesn't redirect to Safari, and then back into the client app. The demo app *does* use SFSafariViewController, and I personally would not recommend implementing anything else. 

To authenticate via SFSafariViewController, simply provide the viewController you want to present the web view from in `authorize(with:presentFrom:success:failure:)` If you set don't provide a viewController in `presentFrom:`, *then* it'll go to the Safari app.

Having multiple instances of a custom built web view is inefficient as `WKWebView` can't and isn't allowed to access the keychain (which SFSafariViewController can use). If you want to support multiple account logins, you have to store the access tokens returned from `authorize(with:presentFrom:success:failure:)` and then repeating it. Storing the access token also means that your users won't have to re-login each time they open the app and can directly use their accounts from the pre-fetched Access Tokens.

**Comment by meteochu** [comment]
This issue was answered over 5 months ago and will now be closed.

**Comment by smhk** [comment]
@meteochu ,

in iOS I am indeed using

`swifter.authorize(withCallback: url, presentingFrom: self, success: { token, response in`

("self" is a normal view controller)

but it is opening the Safari app, rather than using an SFSafariViewController.

Can you think of any reason this could be the case?  It's driving me nuts!

I did import SafariServices up top if that matters;

I just cannot think why it would be going to the external Safari app :/

Using the latest iOS, latest Xcode, etc.

Help!  : O

thanks ...
