### ISSUE TITLE
Swifter Method Naming Convention

### ISSUE THREAD

**Issue by meteochu** [mattdonnelly/Swifter#143]
Swift 3 entered Preview 1 a few days ago, and I thought I'd start things off by pushing a compatibility branch, which can be found at the [swift-3 branch](/mattdonnelly/Swifter/tree/swift-3) in this repo. 

### Part 1, Swift 3 updates

As many of you may know, Swift 3 updated the naming convention to be shorter and clearer. More information can be found on [Swift's API Design Guidelines](https://swift.org/documentation/api-design-guidelines/).

To incorporate this, I am proposing changes to Swifter to match the new guidelines. 

```
// Swift 2.2
public func getStatusesShowWithID(_ id: String, count: Int? = nil, trimUser: Bool? = nil, includeMyRetweet: Bool? = nil, includeEntities: Bool? = nil, success: ((status: Dictionary<String, JSONValue>?) -> Void)? = nil, failure: FailureHandler? = nil) {
// ...
}

// Swift 3.0
public func getStatuses(id: String, count: Int? = nil, trimUser: Bool? = nil, includeMyRetweet: Bool? = nil, includeEntities: Bool? = nil, success: ((status: Dictionary<String, JSONValue>?) -> Void)? = nil, failure: FailureHandler? = nil) {
// ...
}
```

By trimming the `withID` from the method name and moving it to the param name, it shortens the name and makes the method (Swift 3)-ier!

Obviously, this change will mean that anyone using Swifter would have to need to manually update their projects to follow this new naming convention. Regardless, I think it's a good idea to follow the naming conventions of the language and make Swifter's code more readable and clean.

### Part 2, simplifying method names
To go beyond this, I am also proposing an even clearer naming convention. Currently, all Swifter methods are named according to their `REST API` call. For example,

  -  `GET statuses/user_timeline` →  `getStatusesUserTimelineWithCount:`
  -  `POST statuses/update` →  `postStatusUpdate:`
  -  `GET statuses/lookup` →    `getStatusesLookupTweetIDs:`
  - `POST lists/members/destroy` →   `postListsMembersDestroyWithListID:`

Now, what I'm proposing is to make make the methods more _readable_ to those using it. Something similar to the following. Note, these are just examples, and not the absolute proposed solution.

  -  `GET statuses/user_timeline` →  `getUserTimelineTweets(user:  ... )`
  -  `POST statuses/update` →  `postTweet(text: ... )`
  -  `GET statuses/lookup` →    `lookupTweets(ids: ... )`
  - `POST lists/members/destroy` →   `removeListMember(userID: ... )`

Thoughts?

**Comment by zntfdr** [comment]
I absolutely agree with you.

Regarding your examples, we can go a bit further (speaking of both clarity and naming simplification) by introducing a few [External Parameter Names](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Functions.html):

This way, instead of:

- ``getUserTimelineTweets(user: ... )`` we could use ``getTimelineTweets(``**forUser**`` user: ... )``
- ``getStatuses(id: ... )`` we could use ``getStatuses(``**withId**`` id: ... )``

Nevertheless, I love the proposal!

**Comment by meteochu** [comment]
Personally, I don't like having the `withID` or `forUser` as external parameter names. In Swift 2.2, that was very common; however, in Swift 3, they moved it towards an even shorter path. Notice that the external param name does not include is simply `at:` rather than `atIndex:`, omitting the internal param name from the external param name.

```
// Swift 2.2 
array.insertContentsOf(anotherArray, atIndex: 1)
// Swift 3.0
array.insert(contentsOf: anotherArray, at: 1)
```

The new naming convention is driven towards the path of omitting long external parameter names whenever possible. In Swifter's case, that may be difficult as many methods share the same name with different parameters; which is why I suggested having internal parameter names as external ones too. Swift 3 also changes the way external and internal parameters are handled, which is why I think using the `id` or `user` is, in this case, better than `withID` or `forUser` as doing that is simply moving the letters to external parameters, rather than shortening the methods and making it Swift-ier

In Swift 1...
```
func aMethod(name: String) // aMethod("string"), external omitted, internal `name`
func aMethod(for name: String) // aMethod("string"), external `for`, internal `name` 
func aMethod(#name: String) // aMethod(name: "string"), internal and external `name`
```

In Swift 2... 
```
func aMethod(name: String) // aMethod("string"), external omitted, internal `name`
func aMethod(for name: String) // aMethod(for: "string"), external `for`, internal `name` 
func aMethod(name name: String) // aMethod(name: "string"), internal and external `name`
```

In Swift 3...
```
func aMethod(_ name: String) // aMethod("string"), external omitted, internal `name`
func aMethod(for name: String) // aMethod(for: "string"), external `for`, internal `name` 
func aMethod(name: String) // aMethod(name: "string"), internal and external `name`
```

**Comment by zntfdr** [comment]
>  In Swifter's case, that may be difficult as many methods share the same name with different parameters; which is why I suggested having internal parameter names as external ones too. 

Ok, got it, thanks!

Even after reading your last post, I'd say that ``getUserTimelineTweets(user: ... )`` should be ``getTimelineTweets(user: ... )``, don't you think? (For my personal taste, I would put "for" as an external parameter, however, as stated on your quote above, let's keep everything as simple as possible :) ).

**Comment by meteochu** [comment]
Yeah, I think that works. Now, we just need to wait for @mattdonnelly :3

**Comment by mattdonnelly** [comment]
This looks great to me, guys. I much prefer the concise syntax of Swift 3 and think it should with some of the verbosity present in Swifter at the moment

**Comment by mattdonnelly** [comment]
@meteochu I'm not sure what the status of your branch is now, but feel free to make a pull request whenever it's ready

**Comment by meteochu** [comment]
@mattdonnelly Everything I've done can be found on the swift-3 branch right now. 

Currently, I've done some basic migrations to Swift 3; refactored the JSON, SwifterHTTPRequest, and main Swifter class; URL, String, and Dictionary extensions; and, fixed the iOS Demo app. I'll get started on migrating to the new naming convention when I become more free.

Since Swift 3 (and Xcode 8) are both obviously in preview and beta, it's best to keep everything in the swift-3 branch until September when Swift 3 comes out of beta.

**Comment by meteochu** [comment]
Complete as of 497f2d0967fc24cb8dc3b014fb80a29ba0f52dc1
Minor changes can and probably will be made until Swift 3 exits beta later this year.

**Comment by zntfdr** [comment]
Awesome job!

Thank you
