### ISSUE TITLE
Changing JSON Completion Block Handlers 

### ISSUE THREAD

**Issue by meteochu** [mattdonnelly/Swifter#144]
## Issue

Currently, in Swifter, each method's success handler depends on the method itself: multiple status lookup will return a JSON array, a tweet lookup will return a JSON dictionary, search (or anything that includes cursors, will return `([JSON], prevCursor: String, nextCursor: String)`

As convenient as it may seem, this is counter-intuitive as those objects are no longer able to directly use JSON methods for accessing it's properties.

For example, if you fetch a tweet, you'll receive a `Dictionary<String, JSON>` object. When you access the `text` property, you'll have to do this...

```swift
let tweet: [String: JSON] = /* returned tweet object */
if let tweetText = tweet["text"]?.string {
  // ...
}
```
Since `tweet` is a dictionary, and not a `JSON` object, using subscripts will return an `Optional(JSON)`, rather than the standard `JSON` type you would get when you access through a `JSON` object. This makes it slightly redundant to access the `.string` property as it is already an optional value.

## Proposal

Change all (where appropriate) Swifter success handlers to use "raw" `JSON` without using `.array` or `.dictionary` before handing the object to the completion block. This would simplify the process of accessing the values from the JSON. The previous example would then be like the following, with no redundant `?` optional casting involved, making it clearer for the client to use.

```swift
let tweet: JSON = /* returned tweet object */
if let tweetText = tweet["text"].string {
  // ...
}
```

## Changes to Swifter

Current Swifter methods, such as 
```swift
public func showUser(screenName: String, includeEntities: Bool? = nil, success: ((user: Dictionary<String, JSON>?) -> Void)? = nil, failure: FailureHandler) { ... } 
```
will simply be changed to
```swift
public typealias JSONCompletion = (JSON) -> Void

public func  showUser(screenName: String, includeEntities: Bool? = nil, success: JSONCompletion? = nil, failure: FailureHandler) { .. }
```

## Impact

Obviously, anyone using Swifter will have to update their client code accordingly to use the JSON objects instead of the casted ones provided in current versions of Swifter. However, since we're already planning on changing a lot for Swift 3, it's best if we do this now, than later.

**Comment by zntfdr** [comment]
Speaking of JSON: can we please get rid of the JSONInvalid case?

We could just return `nil` where necessary instead (and use [failable initializers](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Initialization.html#//apple_ref/doc/uid/TP40014097-CH18-ID224)).

**Comment by mattdonnelly** [comment]
Definitely in favour of this change. I originally introduced the JSON type to help with accessing nested JSON values, but in the newer versions of Swift this is no longer a problem

**Comment by meteochu** [comment]
@zntfdr I actually find the `.invalid` case very useful, because we're able to chain the JSON without having to optionally cast it. The client should never need to check for .invalid, since they'd just access the values by `.string`, `.object`, `.array`, `.double`, etc; and if the JSON is `.invalid`, it'd just be return nil on its own when accessed through the methods.

**Comment by zntfdr** [comment]
@meteochu you're right:
I was reading the ``JSON.swift`` file and missed the ``.object`` computed property (I haven't used Swifter in a while :sweat_smile: ).

With that property and your explanation ``.jsonInvalid`` makes sense.

Thank you.

Since we're talking about ``JSON.swift``, what about [these](https://github.com/mattdonnelly/Swifter/blob/swift-3/Swifter/JSON.swift#L28) [three](https://github.com/mattdonnelly/Swifter/blob/swift-3/Swifter/JSON.swift#L29) [lines](https://github.com/mattdonnelly/Swifter/blob/swift-3/Swifter/JSON.swift#L31)? 

Can't we embed them inside the ``JSON`` declaration (or in an ``JSON`` extension) as static, even computed, properties?

**Comment by meteochu** [comment]
I took them out when I was doing some stuff over the weekend. (Completely forgot to push it, oops)
I've also renamed all the enum cases to remove the redundant `json` title in it.
Check out [the swift-3 branch JSON.swift](https://github.com/mattdonnelly/Swifter/blob/swift-3/Swifter/JSON.swift)

**Comment by zntfdr** [comment]
Great job, thank you!

**Comment by meteochu** [comment]
Complete as of 2024e35905efeaf7509bc1fbbf5eac2a06213142
