### ISSUE TITLE
Twitter Callback does not open the Mac App

### ISSUE THREAD

**Issue by aaalveee** [mattdonnelly/Swifter#148]
I have dragged all Swift components to my app. In twitter app settings page I have given callback url as `mywebsite.in`.

I have added `URL Scheme` like this in `App Delegate`.

```
        NSAppleEventManager.sharedAppleEventManager().setEventHandler(self, andSelector: #selector(AppDelegate.handleEvent(_:withReplyEvent:)), forEventClass: AEEventClass(kInternetEventClass), andEventID: AEEventID(kAEGetURL))
        LSSetDefaultHandlerForURLScheme("appname", NSBundle.mainBundle().bundleIdentifier! as NSString as CFString)
```

And handled the callback like this.

```
func handleEvent(event: NSAppleEventDescriptor!, withReplyEvent: NSAppleEventDescriptor!) {
        Swifter.handleOpenURL(NSURL(string: event.paramDescriptorForKeyword(AEKeyword(keyDirectObject))!.stringValue!)!)
    }
```

And I give request to Twitter using my consumerKey and consumeSecret.

```
  //MARK: Connect Twitter

    @IBAction func connectTwitterTapped(sender: NSButton)
    {
        let swifter = Swifter(consumerKey: "someRandomValue", consumerSecret: "someRandomValue")
        swifter.authorizeWithCallbackURL(NSURL(string: "appname://success")!, success: { tokenSet, _ in

            Thread.main({

                print(tokenSet?.secret)
                print(tokenSet?.userID)
                print(tokenSet?.verifier)
                print(tokenSet?.key)

                let vc = NSStoryboard(name: "Storyboard", bundle: nil).instantiateControllerWithIdentifier("WritingTweetsID") as! WritingTweets
                self.presentViewControllerAsModalWindow(vc)

            })

            }, failure: self.failureHandler)
    }
```

What I could see is that, the app successfully redirecting to Twitter app authorisation page in default web browser, when I click on `Authorise` it takes me to the window where my app currently present, but it didn't open my app. As in I have a break point in `handleEvent` method in `App Delegate`, it never stopped on that breakpoint, also never posted any notification. 

I downloaded the original project and checked it works fine. As I could see that I have followed the same in my app too, But somehow it is not working. 

Would you mind helping me out, any suggestions? Am I missing something in my project?

**Comment by robmontesinos** [comment]
I've had the same problem with macOS app for the last few days. I hope that you guys can help. 

- My appDelegate code is similar to the above except I used "swifter" for urlScheme. 

- The callbackHandler is the same as above and the macOS demo. 

- ViewController code is similar to above except I'm using "swifter://success"

- I copied the info.plist entry from another issue:
`<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>swifter</string>
			</array>
		</dict>
	</array>
`
- Twitter dashboard entry includes a firebase callback url which has the required 'https://xxxxx'
- I added "swifter://" to twitter dashboard as well (thanks to help I found in a different issue) and got a little bit further in the authentication sequence but came across this roadblock as per screenshot below:
<img width="671" alt="Screen Shot 2019-04-15 at 9 14 03 PM" src="https://user-images.githubusercontent.com/258556/56182044-0e9ee080-5fc5-11e9-84de-92abddeb9880.png">

I would really appreciate some help to finally get to playing with this very cool library. Thank you.

**Comment by robmontesinos** [comment]
It started working but unfortunately I am not sure what I did. Maybe it was adding the identifier or switching Role to 'Viewer' - I think my problem had nothing to do with Swifter but with my not knowing how to make Safari talk to my macOS app. I'll throw up a screenshot just in case it helps someone else. Salud!
<img width="924" alt="Screen Shot 2019-04-15 at 9 53 17 PM" src="https://user-images.githubusercontent.com/258556/56182961-4019ab00-5fc9-11e9-998b-a8fd4ec4bbcc.png">
