### ISSUE TITLE
Get raw data (NSData/NSString) from JSON

### ISSUE THREAD

**Issue by bluekemon** [mattdonnelly/Swifter#152]
Hi,

I want to store tweets (JSON) as an array of NSString or NSData (and not array of JSONValue). I got raw NSString for a tweet using the 'description' property. Now I'm having trouble converting it back to JSONValue format so it's parameters can be accessed. 

Is there a way to get raw JSON data and then convert it back to the Swifter's JSONValue format? Would be a big help.

**Comment by zntfdr** [comment]
Hi @bluekemon , 
have you tried using the ``parseJSONString`` method? You can find it [here](https://github.com/mattdonnelly/Swifter/blob/master/Swifter/JSON.swift#L244)  :)

**Comment by bluekemon** [comment]
Hey @zntfdr,

I did try **parseJSONString** and **parseJSONData** after I saw them being used in Swifter.swift file. But Xcode throws an error - "Type 'JSON' has no member 'parseJSONString'". I've imported SwifteriOS in my file, so why can't Xcode see the functions?

**Comment by zntfdr** [comment]
It's a ``static`` JSON function:
in order to call it you have to write``JSON.parseJSONString (...)``, please let me know if it works :)

**Comment by bluekemon** [comment]
Yes, was doing exactly that. Apparently Xcode is not able to "see" the **parseJSONString** method, or any other public test methods that I add to JSON.swift. Am I forgetting to include some file?

**Comment by zntfdr** [comment]
Well, that's strange!
Can you see the ``JSON`` enum at all? Can you access to any of the JSON instance properties?

If not, then the file probably is not included among the targets of your build.

**Comment by meteochu** [comment]
Actually, the `parseJSONString` and `parseJSONData` methods have been left as `internal` and not `public`. Also, using the `.description` property on the JSONValue will not give you the "raw string" you're looking for, but simply a parsed string generated by JSON (which is not reversible). 

In order to achieve what you want, here's how I would do it:

Instead of using `JSONValue`, create a wrapper class that simply takes the values you need. Inherit `NSCoding` so that you can convert the class object to `NSData` using `NSKeyedArchiver`

When you need to do the reverse and convert them back into the wrapper class, you'll just need to use `NSKeyedUnarchiver`.

Read more about `NSCoding`, `NSKeyed(Un)Archiver` [here](http://nshipster.com/nscoding/)

**Comment by bluekemon** [comment]
@zntfdr and @meteochu : Thanks so much for your help! I will try both these things and see if it works.

**Comment by annjawn** [comment]
It would actually be great to have `Codable` / `Decodable` support for this. So just getting the `Data` is actually going to be a heck of a lot more convenient right now. With `Codable` it's going to be a piece of cake to get what we want from the resulting JSON. The `JSON` type is a lot of un-necessary overhead to parse through to get what we want. Simply returning `Data` would be much helpful.

**Comment by zachrwolfe** [comment]
I have a pull request #203 that addresses this issue. I've since thought of a better, simpler way to approach it but haven't had time to implement that, so it's been sitting idle. I plan to revisit soon!

**Comment by annjawn** [comment]
@zachrwolfe I completely agree. A merge of your PR would be great addition to the lib. Until then, I'll have to try out your commit (87a8625).

**Comment by annjawn** [comment]
Here I am chasing the chicken (using `Decodable`). Slightly inefficient, but works.

```
swifter.getUserFollowing(for: .id("16532709"), cursor: nil, count: nil, skipStatus: true, includeUserEntities: false, success: { (json, prev, next) in
     let jsonData = String(describing: json)
     let jsD   = jsonData.data(using: .utf8)!
     do{
            let json = try JSONDecoder().decode([userIDS].self, from: jsD)
          }catch{
                    print("ANN: JSON Error")
         }
      }, failure: { (error) in
                print("ANN: Error ", error.localizedDescription)
            })
```

**Comment by zachrwolfe** [comment]
Haha, whatever works I guess 😆
