### ISSUE TITLE
Twitter OAuthEchoHeadersToVerifyCredentials

### ISSUE THREAD

**Issue by alexsanderkhitev** [mattdonnelly/Swifter#154]
Hello! Thank you for your library. How can I get the OAuthEchoHeadersToVerifyCredentials via this library? Please help me.

I try like 

```
    func auth() {
        let swifter = Swifter(consumerKey: twitterKey, consumerSecret: twitterSecret)
        guard let callBackUrl = NSURL(string: "com.*****://success") else { return }
        swifter.authorizeWithCallbackURL(callBackUrl, presentFromViewController: nil, success: { (accessToken, response) in
            if accessToken != nil {
                swifter.getAccountVerifyCredentials(false, skipStatus: true, success: { (myInfo) in
                    print("swifter", myInfo)
                    }, failure: { (error) in
                        print(error.localizedDescription)
                })
                }
            }) { (error) in
                print("swifter", error.localizedDescription)
        }
    }

```
I made like, it works but how can I get the OAuthEchoHeadersToVerifyCredentials? Please help me.

**Comment by meteochu** [comment]
If I'm not mistaken, you're referring to [this method from TwitterKit](https://dev.twitter.com/twitter-kit/ios-reference/twtroauthsigning). This method doesn't exist in Swifter, nor does it need to. Swifter manages all the OAuth headers internally, therefore, any `Swifter` instance that has a valid OAuthToken and OAuthSecret will allow you to use the API.

**Comment by alexsanderkhitev** [comment]
Hello @meteochu ! Can you tell me how can I update OAuthEchoHeaders from TwitterKit? I post OAuthEchoHeaders to our server but our server detected it like old data. I tried several different methods but I didn't get any good result. We should post OAuthEchoHeaders when we do any request to our server. Please help me.

**Comment by zntfdr** [comment]
Dear @alexsanderkhitev , I'm sure @meteochu will answer if he has some experience on it.

However, I'd like to kindly remind you that this is the repository for **Swifter**: 

if you have any questions regarding **TwitterKit** (that is not linked to Swifter in any way), please ask for assistance to the [TwitterKit community](https://twittercommunity.com/c/fabric/twitter), where you can find many other developers that may have solved the same issues you're facing already .

Another option is to look for answers in [StackOverflow](http://stackoverflow.com/questions/tagged/twitter-fabric).

If you have any questions regarding Swifter, please let us know: we will be more than happy to help you out :smile:

**Comment by alexsanderkhitev** [comment]
Hello @zntfdr . Thank you so much=)
