### ISSUE TITLE
How to retrieve tweets from a user ?

### ISSUE THREAD

**Issue by sohaeb** [mattdonnelly/Swifter#156]
Hey guys, I'm new to Swifter. I really appreciate the hard work you have done to make this for us. 

I already got the consumer key and secret key. But I don't know how to retrieve the tweets from a specific timeline (say: "microsoft" twitter account)

This is what I have done so far (I hope i'm on the right direction)

```
let swifter = Swifter(consumerKey: "consumerKey",
 consumerSecret: "secretKey",
 appOnly: true)
        
        
        swifter.getStatusesUserTimelineWithUserID("12345",
 count: 1,
 sinceID: nil,
 maxID: nil,
 trimUser: false,
 contributorDetails: false,
 includeEntities: false,
 success: { (statuses) in
        
     //What do I write here

            }) { (error) in
                
        }

```

PS: Is it possible to just add 1 example on how to retrieve simple JSON values (name, tweet, etc..) to the docs ? This would extremely helpful since I can learn a lot from just reading 1 example of code. Thank you

**Comment by meteochu** [comment]
Hello! Thanks for your interest in Swifter. To know which values to get, check Twitter's [REST API Documentation](https://dev.twitter.com/rest/public). Currently, Swifter is going through major transitions with the introduction of Swift 3, and those changes will be merged into the `master` branch once Swift 3 becomes publicly available (and out of beta).

Right now, `getStatusesUserTimelienWithUserID:` will return an array of `JSONValue` objects; each object in the array represent a tweet object retrieved from Twitter. To know how to get, say, the `id` of the Tweet, check the documentation on [Tweet objects](https://dev.twitter.com/overview/api/tweets), which will show you that it's the `id_str` key. e.g.
```swift
// statuses is a Array<JSON>
if let tweetID = statuses[0]["id_str"].string {
  // ... 
}

```

**Comment by zntfdr** [comment]
edit: I was writing this answer when @meteochu answered first, anyway, I believe this can add some more insights. 

Hi @sohaeb , ask and it shall be given :smile:  :

you can find the example [here](https://github.com/mattdonnelly/Swifter/blob/master/SwifterDemoiOS/TweetsViewController.swift#L53).

Basically, ``statuses`` is an array of ``JSONValue``: 
each ``JSONValue`` is a _parsable_  ``JSON`` structure via the [JSON enum](https://github.com/mattdonnelly/Swifter/blob/master/Swifter/JSON.swift).

...I was going to write more but, with @meteochu answer, there's no need anymore!

If you have any other questions, we're here to help! :+1:

**Comment by sohaeb** [comment]
thanks you guys. This is what I was looking for
