### ISSUE TITLE
App rejection due to IPv6 support

### ISSUE THREAD

**Issue by lelinho** [mattdonnelly/Swifter#160]
It works well in all my tests, but I can`t test in a IPv6 only network.
I just use Swifter.

Can you tell me if Swifter supports IPv6?

Thanks

**Comment by meteochu** [comment]
Is this due to IPv6 support or the lack thereof?

**Comment by lelinho** [comment]
lack of support.

But I think it is streaming api rate limits. The error messages are coming wrong in xcode 8 GM, always I get "SwifteriOS.SwifterError error 1"

**Comment by meteochu** [comment]
I'll check it out when I have time. If you manage to find the source of error and fix it, feel free to open a pull request, and I'll merge it.

**Comment by meteochu** [comment]
I completely forgot to respond to this. 
I was unable to find any issues related to IPv6 since Swifter goes through URLSession, which natively supports IPv6. This issue will now be closed.
