### ISSUE TITLE
Can't compile Swifter

### ISSUE THREAD

**Issue by caleb0** [mattdonnelly/Swifter#161]
Cloned the repository, opened the xcodeproject and pressed play, got 200 errors.

Am I doing something wrong?
http://i.imgur.com/bIer0fl.png

**Comment by zntfdr** [comment]
Hey hi!
That doesn't look right hehe
Quick question: are you using Xcode 8?

**Comment by meteochu** [comment]
That's definitely not Xcode 8. 
Swifter is updated for Swift 3, which requires Xcode 8. You can download (or update) it from the Mac App Store.

**Comment by caleb0** [comment]
Excellent, thank you very much
