### ISSUE TITLE
Swifter Pod

### ISSUE THREAD

**Issue by tonygon** [mattdonnelly/Swifter#162]
Hello, 
I think it would be very beneficial if you guys made Swifter a Pod.
It would be easier to install and to manage as dependency.

Thanks!

**Comment by ht22pt** [comment]
I have add this feature to pull request #166

**Comment by markymark1988** [comment]
@mattdonnelly ^

**Comment by meteochu** [comment]
Completed as of 7ddeabb01ce00c4cc793a42218fca951b1cb94ef
