### ISSUE TITLE
Tell if tweet is retweet

### ISSUE THREAD

**Issue by milesper** [mattdonnelly/Swifter#165]
Is there any way to tell if a tweet is a retweet? The "retweeted" bool doesn't seem to be changing.

**Comment by meteochu** [comment]
IIRC the `retweeted` value returns if the user has retweeted that tweet.
If you want to check if a tweet is a RT, then check for the existence of `retweeted_status`

If `retweeted_status` has a value, then it is a retweet, or else it's `null`.

**Comment by milesper** [comment]
I tried this, but every time it checks if retweeted_status has a value it returns true, yet the `retweeted_status` object is "invalid". Should I be checking if the JSON object is equal to Invalid? Also, `retweeted` doesn't seem to ever be returning true, even when a tweet has a value for `retweeted status`.

**Comment by meteochu** [comment]
Note that `retweeted` and `retweeted_status` are completely different things. 
`retweeted` is only true if the authenticated user has retweeted that tweet (regardless if it was a retweet or not).

`retweeted_status` is `null` (aka `Invalid` in Swifter.JSON) if it is not a retweet, and is a JSON object if it is a retweet.

**Comment by meteochu** [comment]
This issue has been answered and is now 2+ months old. It will now be closed.

**Comment by lev-kusanagi** [comment]
Hi @meteochu ! It seems retweeted_status is not returning Invalid if it's not a retweet.

**Comment by lev-kusanagi** [comment]
It does return .invalid but couldn't check. #286 fixes it
