### ISSUE TITLE
Facebook 

### ISSUE THREAD

**Issue by davidseek** [mattdonnelly/Swifter#167]
This library is purely amazing. Finished my complete Twitter integration within hours.
By any chance. Do you have a similar project for Facebook? @mattdonnelly

**Comment by meteochu** [comment]
Twitter and Facebook are separate projects. The reason we have Swifter for Twitter is because Twitter does not offer the framework; on the other hand, Facebook does have their framework for using the [Facebook SDK](https://github.com/facebook/facebook-sdk-swift).

**Comment by davidseek** [comment]
I know that those are different projects... That's why I was asking for `something similar`. And I know about the Facebook SDK. But you can't compare a shitty Framework like the SDK with this awesome baby...
