### ISSUE TITLE
How to get Users's Info

### ISSUE THREAD

**Issue by davidseek** [mattdonnelly/Swifter#168]
I'm really searching since an hour now. How do I get current User's (or by UserID), Account information? Like Name, profile pic, followers count. What function do I need to use?

**Comment by zntfdr** [comment]
Have you tried https://github.com/mattdonnelly/Swifter/blob/master/Swifter/SwifterUsers.swift#L256 ?

**Comment by davidseek** [comment]
Thank you! That was, what I was looking for.
