### ISSUE TITLE
getTimeline function -> parameter userID unused?

### ISSUE THREAD

**Issue by davidseek** [mattdonnelly/Swifter#169]
I am confused.

When I use the `getTimeline` with my Twitter UserID, I receive my feed. As expected.
But by accident, I just used an empty String instead my userID sent as parameter and I still got my feed.

Also I have just tried to send the String `lol` instead of a valid `userID`, still got my feed. Is that a wanted behavior?

I'm talking about that function:

```
public func getTimeline(for userID: String, count: Int? = nil, sinceID: String? = nil, maxID: String? = nil, trimUser: Bool? = nil, contributorDetails: Bool? = nil, includeEntities: Bool? = nil, success: SuccessHandler? = nil, failure: FailureHandler? = nil) {
        let parameters: Dictionary<String, Any> = ["user_id": userID]

        self.getTimeline(at: "statuses/user_timeline.json", parameters: parameters, count: count, sinceID: sinceID, maxID: maxID, trimUser: trimUser, contributorDetails: contributorDetails, includeEntities: includeEntities, success: success, failure: failure)
}
```

It does not matter what String I send as `for userID: String`, it always returns MY feed.

**Comment by meteochu** [comment]
If you send a valid `userID`, it will return the correct user.
It is _normal_ Twitter behaviour to send your Twitter feed if you supply an invalid `userID`, it's not a Swifter issue.

**Comment by davidseek** [comment]
Okay. So if the ID is valid, I get the feed from the ID, if not, I receive my home feed?

**Comment by meteochu** [comment]
That is correct.
