### ISSUE TITLE
How to handle Token expiration

### ISSUE THREAD

**Issue by davidseek** [mattdonnelly/Swifter#170]
I have just tried to change my Twitter password to force a Token expiration. Sadly it did not happen. It does with Instagram tho.

My plan was to catch the error message and then delete the credentials from my backend and let the user re-auth. Buuuuuuut since I was not able to force a Token expiration, I have no idea what to do now.

What's the best practise to handle token expiration?

Currently I'm not checking if the token is valid. I'm downloading the credentials from my backend and am instantiating Swifter with them. I expect no crash, but I'm sure that the logic downloading the feed and stuff will stop working...

Any ideas/suggestions?

**Edit: I have just tried `verifyAccountCredentials` func, but the json does not include `HTTP 200/401`, the json is my Twitter user acc.** That has to be a bug?

**Comment by meteochu** [comment]
IIRC, Twitter tokens don't expire, even if the user changes passwords. You have to remove the authenticated tokens from `Twitter > Settings > Apps`

Additionally, `verifyAccountCredentials` returns your Twitter use if the credentials are valid, and null if it is invalid. Thus, if it returns your JSON, it means it's valid.
