### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Goro-Otsubo** [mattdonnelly/Swifter#173]
I downloaded the whole project. Tried to build macOS demo project. Xcode returned the error "could not read data from '/XXXX/Swifter-master/Swifter/Info.plist': The file “Info.plist” couldn’t be opened because there is no such file."

Seems to me that when moved source files to "source" directory, something went wrong. Workaround is make "Swifter" directory and copy info.plist file from "source" directory.

**Comment by dosunhour** [comment]
@Goro-Otsubo it missing plist attach with it framework. Just go to Project Target:  Example: I build it on iOS, so select SwifteriOS( In Target ) -> General -> Choose plist file in the Source Directory. 
Hope it help.

**Comment by Goro-Otsubo** [comment]
It worked! Thanks..
