### ISSUE TITLE
Post tweet source with ACAccount

### ISSUE THREAD

**Issue by perteraul** [mattdonnelly/Swifter#174]
I'm using Swifter in an utility that tweets and I've been wondering how can I pass to Twitter the source of the tweet. Currently, in Tweetbot, tweets sent from my app show „via iOS”.

**Comment by meteochu** [comment]
In order for Twitter to recognize your app, you must be using application tokens (Token & Secret) from Twitter API. Using ACAccount to tweet is using the system's application token & secret, which is why it shows up as "via iOS"

**Comment by perteraul** [comment]
I see. I'll convert to that option then. 

Thanks!
