### ISSUE TITLE
Last version on Cocoapods

### ISSUE THREAD

**Issue by shoheiyokoyama** [mattdonnelly/Swifter#180]
The last version available on Cocoapods is still [1.3.2](https://cocoapods.org/?q=Swifter) 
Would be great to push the last podspec if it's not an issue for you.

Thanks!

**Comment by klemenzagar91** [comment]
If you use it like this, it works.
`pod 'Swifter', :git => 'https://github.com/mattdonnelly/Swifter.git'`
