### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by mbagliojr** [mattdonnelly/Swifter#181]
When I attempt to implement Logout, i get the message "HTTP Status 401: Unauthorized, Response: Error processing your OAuth request: Invalid oauth_verifier parameter". I have tried creating a new swifter object on logout as well as reusing the previous one and in both cases I get this exception. If I then close the app and reopen it, it works correctly. How do I go about clearing the swifter object?

**Comment by mbagliojr** [comment]
`@IBAction func didTouchUpInsideLoginButton(_ sender: AnyObject) {
        let failureHandler: (Error) -> Void = { error in
            self.alert(title: "Error", message: error.localizedDescription)
            
        }
        
        if useACAccount {
            let accountStore = ACAccountStore()
            let accountType = accountStore.accountType(withAccountTypeIdentifier: ACAccountTypeIdentifierTwitter)

            // Prompt the user for permission to their twitter account stored in the phone's settings
            accountStore.requestAccessToAccounts(with: accountType, options: nil) { granted, error in
                guard granted else {
                    self.alert(title: "Error", message: error!.localizedDescription)
                    return
                }
                
                let twitterAccounts = accountStore.accounts(with: accountType)!
                
                if twitterAccounts.isEmpty {
                    self.alert(title: "Error", message: "There are no Twitter accounts configured. You can add or create a Twitter account in Settings.")
                } else {
                    let twitterAccount = twitterAccounts[0] as! ACAccount
                    
                    UserDefaults.standard.set(twitterAccount, forKey: "account")
                    
                    session().swifter = Swifter(account: twitterAccount)
                    let tweetsViewController = self.storyboard!.instantiateViewController(withIdentifier: "TweetsViewController") as! TweetsViewController
                    self.navigationController?.pushViewController(tweetsViewController, animated: true)
                }
            }
        } else {
            let url = URL(string: "swifter://success")!
            
            session().swifter.authorize(with: url, presentFrom: self, success: { handler in
                
                UserDefaults.standard.set(handler.0?.key, forKey: "key")
                UserDefaults.standard.set(handler.0?.secret, forKey: "secret")                
                
                let tweetsViewController = self.storyboard!.instantiateViewController(withIdentifier: "TweetsViewController") as! TweetsViewController
                self.navigationController?.pushViewController(tweetsViewController, animated: true)
                }, failure: failureHandler)
        }
    }`

**Comment by mbagliojr** [comment]
and logout. I have tried it with the self.swifter line commented out and not commented out... 

`

func logout() {
        self.swifter = Swifter(consumerKey: "HIDDEN", consumerSecret: "HIDDEN")

        UserDefaults.standard.set(nil, forKey: "key")
        UserDefaults.standard.set(nil, forKey: "secret")
        UserDefaults.standard.set(nil, forKey: "account")
    }`

**Comment by zntfdr** [comment]
Replacing the ``Swifter`` object should do the trick.

What about removing the userDefaults values first, and then create a new ``Swifter`` object?

**Comment by mbagliojr** [comment]
It still did not work. I do have a workaround but it feels hacky. The error still comes in so in my failure handler, I'm checking what the failure kind is and just ignoring it if it is of type 401 and moving on. Oddly enough, I'm still getting a new key and secret as well as the error... I believe this is a bug in the library or at very least a bug in the example application, as my code is virtually identical to the example.
