### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by harlanhaskins** [mattdonnelly/Swifter#185]
Hi! I'd love to be able to use Swifter on Linux to write twitter bots, but this library seems to rely on AppKit specific stuff. I'd be willing to take a crack at adding Linux compatibility if you're up for it.

Thanks!

**Comment by zntfdr** [comment]
Hey Harlan! Nice to see you here 😄 

Please feel free to go ahead! You have all my support 💯

**Comment by meteochu** [comment]
PR #187 is now merged, thanks!
