### ISSUE TITLE
Media upload issues

### ISSUE THREAD

**Issue by bvjustin** [mattdonnelly/Swifter#192]
The media/upload.json endpoint returns a 204 status code and an empty response on an "APPEND" command during a chunked upload.  This successful empty response is interpreted as a failure in Swifter (throws an exception parsing empty data) in the jsonSuccessHandler.

The mulipartContent function in SwifterHTTPRequest.swift adds an extraneous "\r\n" to the end of the data, which causes chunked media uploads to fail with the Twitter API error "Segments do not add up to provided total file size". These 2 bytes stumped me for 2 solid days. :) 

Filename in multipartContent Content-Disposition is set to "Optional(MyFilename)" due to use of String(describing:filename)

Charset in Content-Type header set to "Optional(utf-8)" same as above.

Swifter.DataParameters.fileNameKey is left in the parameters dictionary in Accounts and OAuth clients. Should be removed.

**Comment by meteochu** [comment]
This was already addressed in #193, closing this issue now.
