### ISSUE TITLE
No way to specify extended mode

### ISSUE THREAD

**Issue by JTP3XP** [mattdonnelly/Swifter#197]
If you want to be able to get the full text of a truncated tweet, it seems like you need to make a request in extended mode (which may be the default in the future):
[Twitter documentation](https://dev.twitter.com/overview/api/upcoming-changes-to-tweets)

I don't see a way to do this in Swifter yet - is this something that should be added?

**Comment by zntfdr** [comment]
I believe this extended mode should be the new default, with the option to get the truncated tweet if needed. 

All theres's to do is add the ``tweet_mode=extended`` parameter isn't it?

**Comment by JTP3XP** [comment]
That should be it, yes. The other option for that parameter is `compat`, which is just the current behavior and will always limit the tweet text to 140 characters to avoid breaking anything that relies on 140 being the maximum length of the text.

**Comment by JTP3XP** [comment]
This is actually a pretty disruptive change - the response with `tweet_mode=extended` does not include a `text` field, but has a `full_text` field instead. So making this the default would break any existing code that references `text`. Given this, should the default remain Twitter's default (so `tweetMode: String? = nil` in the function definitions, which is nice and consistent with the other parameters), or do you still think the default should change now to `extended`?

**Comment by meteochu** [comment]
The whole reason Twitter chose to add `tweet_mode=extended` was so that it does not break any legacy code; neither should we. We can simply add an enum that specifies the `tweetMode` attribute and have it default to the original.

**Comment by JTP3XP** [comment]
If we force it to default to the original, Swifter's behavior will differ from Twitter's in the future once Twitter decides it is ready to break the legacy code and `extended` becomes the default. If we implement this with a parallel structure to the other parameters (default to `nil` and use the `??=` operator to conditionally add to the parameters array) then Swifter's behavior will always match Twitter's default behavior. This wouldn't require adding a enum, so I think this is a simpler change and more straightforward in the long-term.

**Comment by zntfdr** [comment]
I'm with @JTP3XP in this one: Twitter intentions are clear and point to use the ``extended`` mode from now on. 
The sooner our apps adapt, the better! 😄

**Comment by JTP3XP** [comment]
I agree that our apps should adapt, but in this case I think they should be adapting on Twitter's schedule, not ours. To that end, I'm proposing the default would remain not specifying either mode, just like all other parameters in the framework, but after this change everyone would have the option to opt into `extended`. To me this seems like the most consistent solution with the rest of the framework; it makes no decisions for you, it just facilitates interacting with the Twitter API.

**Comment by buddax2** [comment]
please review PR [211](https://github.com/mattdonnelly/Swifter/pull/211). It still in compatibility mode by default but you easily can get extended tweets by adding `tweetMode: .extended` to the getTimeLine()
