### ISSUE TITLE
Need help installing in XCode 9

### ISSUE THREAD

**Issue by annjawn** [mattdonnelly/Swifter#214]
I pulled the Swifter.xcodeproj , how do I embed the iOS framework after that. I tried with a bridging header with as suggested in #121 but still no luck and I keep getting an error that `Swifter/Swifter-Bridging-Header.h` not found.

**Comment by annjawn** [comment]
Nevermind, didn't know there is a pod available until I scoured the Issues section. Updating the Documentation would be helpful. Thanks.

**Comment by zachrwolfe** [comment]
Personally I just added the project to my xcworkspace, then went in project settings and added it to "Embedded Binaries". But you're right, the pod should be mentioned in the readme.
