### ISSUE TITLE
Getting user's entire timeline / TwitterKit interoperability

### ISSUE THREAD

**Issue by annjawn** [mattdonnelly/Swifter#215]
Currently `getHomeTimeline` gets the `count` number of recent tweets from the user's timeline,like this one gets the first 100.

`self.swifter.getHomeTimeline(count: 100, success:...`

Is there a way to refresh the `UITableView` with the next 100 as the user scrolls up just like the `TWTRTimelineViewController` that comes with TwitterKit (latest version)? Also, is there a way (could be an enhancement) to just pull the user's entire timeline as a JSON with just the Tweet IDs? This way the Tweet IDs can be used to construct a `TWTRTweetTableViewCell` to populate the tableview cells without having to worry too much about creating a custom cell with variable height, media (photo,video)  etc. This could greatly expand the interoperability of this library with TitterKit. 

As it stands now,  `TWTRTimelineViewController` is a subclass of a `UITableViewController` with extremely limited customizability, is a ViewController level implementation, and often times buggy. As opposed to this the `TWTRTweetTableViewCell` in `TWTRTweetViewStyleCompact` mode is a much better option to implement in a custom TableView and gives far more control over customization without too much overhead but as per the out of the box implementation it needs a predefined set of Tweet IDs to be able to grab the tweets and that's where Swifter might come in handy in supplying the Tweet IDs as a continuous stream.

**Comment by zachrwolfe** [comment]
> Is there a way to refresh the UITableView with the next 100 as the user scrolls up...

A brief overview:
- Add a UIRefreshControl to your table view controller if there isn’t one already
- Add a target to the refresh control so you can execute code when the user scrolls up past the top of the table view
- In that target method get the newest tweets, which can be done by taking the most recent id currently loaded (the first one) and passing it as the sinceID parameter to getHomeTimeline() 
- Insert the new tweets (if there are any) into your data model and notify your table view.

> Also, is there a way (could be an enhancement) to just pull the user's entire timeline as a JSON with just the Tweet IDs?

Hmm... I might not be fully understanding your question but I don’t think you need to do this. From what I can glean from the TwitterKit docs you should be able to construct a TWTRTweet from a tweet object you get from Swifter, then configure your TWTRTweetTableViewCell using that TWTRTweet by calling configure(with:).

Feel free to ask further questions if I’m not making sense.

**Comment by annjawn** [comment]
@zachrwolfe yes I think I spoke too soon. I was able to Build `TWTRTweet`s using the JSON from the API and the `since_id` and `max_id` would do the job of refreshing or scrolling behavior as I mention. Although, I am still unable to use Swifter because I am using Twitter `sharedInstance().login` to authenticate via Firebase Call back and I am not sure how to make the two of them work together since my Swifter instance would need a separate authentication of it's own.

**Comment by zachrwolfe** [comment]
If you want a singleton accessible from anywhere, you can just add a static property to Swifter via an extension, and initialize it to a Swifter instance using your API keys. Then after authorization you can use it to get data from the API just like you would with `Twitter.sharedInstance()`.

**Comment by annjawn** [comment]
So are you saying that Swifter won't need the ACAccount object? Because I won't be able to create once since my authentication is happening via sharedInstance().login. If just initialize a Swifter object using the access keys how will it know which user data to pull or would it just behave like a guest? Or is there a way to create an ACAccount object using the sharedInstance().session? By the way, Twitter documentation suggests that ACAccount is deprecated from iOS 11 onwards, but for some reason it still works.

**Comment by zachrwolfe** [comment]
Yeah, it's not necessary to use `ACAccount`, and you're right that it's deprecated. Seems I misunderstood you slightly, as in my answer I was referring to using purely Swifter for authorization. If you want to use TwitterKit for auth, you can set `client.credential` on your Swifter instance to a new `Credential` object using the `authToken` and `authTokenSecret` on your `TWTRSession`.

**Comment by annjawn** [comment]
Awesome. I will give it a try. Thanks for the help.
