### ISSUE TITLE
Cant get accounts on High Sierra

### ISSUE THREAD

**Issue by SS-HU** [mattdonnelly/Swifter#216]
Hi Matt!

Keep getting "There are no Twitter accounts configured. You can add or create a Twitter account in Settings." when requesting the accounts when on high Sierra. Does this mean that connecting with ACAccounts is no longer working, or are there any special requirements needed?

**Comment by andypiper** [comment]
I believe High Sierra removed Twitter integration (as did iOS 11) so you'll probably need to roll your own OAuth flow.

**Comment by SS-HU** [comment]
Dear Mr Piper. 

We meet again at last. Such a small world after all. What an unusual pleasure. Been a long time. 
How are things going?
 
Wonder if our fun last year had anything to do with the corrupt cutting out their entire social life. 
Somehow though, as claimed then, claiming now the facts of things, which perhaps would be easier to communicate without the public nightmares. 

Perhaps suggesting a meeting point to discuss collaboration would be in place (please do forward the request to the powers to be)?

Thank you for your time and response. : )

Kindest regards SS
