### ISSUE TITLE
All my requests break at SHA1DigestWithKey func

### ISSUE THREAD

**Issue by rgaliu** [mattdonnelly/Swifter#22]
Everytime I try to run this code, it breaks:

```
    var swifter = Swifter(consumerKey: "MY_API_KEY", consumerSecret: "MY_SECRET_KEY")
    swifter.getListsStatuesWithSlug("xxxxxx", ownerScreenName: "xxxxxx", sinceID: nil, maxID: nil, count: nil, includeEntities: false, includeRTs: false, success: {

        (lists: [JSONValue]?) in


        }, failure: {

            (error: NSError) in

            NSLog(" error => %@ ", error.userInfo)

    })
```

It seems to do this with a few other swifter functions I have tried, none of them have worked so far.

It breaks in the SHA1DigestWithKey func in the Swifter+String.swift class:
CCHmac(CCHmacAlgorithm(kCCHmacAlgSHA1), keyStr!, keyLen, str!, strLen, result)

EXC_BAD_ACCESS(Code = 1, address = 0x14)

**Comment by Farranco** [comment]
Thank you, it was not obvious that you needed to follow it with authorizeAppOnlyWithSuccess, assumed incorrectly it would do it automatically by setting the appOnly parameter. It would be beneficial to have that second line included in the read me file for the app only sample code.
