### ISSUE TITLE
Streaming API Code sample

### ISSUE THREAD

**Issue by annjawn** [mattdonnelly/Swifter#220]
Hi,

I am trying to get the streaming api working and the code that I have so far is as below.

I have this method inside a singleton as suggested by @zntfdr [here](https://github.com/mattdonnelly/Swifter/issues/97#issuecomment-185216719)

when I call this singleton method from my VC I do not see any responses at all in the print. Is there something I am missing here?

I sometimes get this error message `HTTP Status 420: Enhance Your Calm, Response: Exceeded connection limit for user` which tells me that my connection is being established (or not). Do i need to put more tracker terms to see any significant streaming?

```
func start(){
        
        let tracker = ["#PSX2017"]
        guard connection == nil else { return }
        print("ANN - friends list :", self.idList)
        if let sess = Twitter.sharedInstance().sessionStore.session() {
            let swifter = Swifter(consumerKey: myKey, consumerSecret: mySecret, oauthToken: sess.authToken, oauthTokenSecret: sess.authTokenSecret)
            print("Starting stream")
            self.connection = swifter.postTweetFilters(follow: nil, track: tracker, locations: nil, delimited: false, stallWarnings: true, filterLevel: nil, language: nil, progress: { (json) in
                print(json)
            }, stallWarningHandler: { code, message, percentFull in
                print("ANN: Stall error ", message!)
            }, failure: { error in
                let err = error as! SwifterError
                print("ANN: Error ", err.message)
            })
        }
    }
```

**Comment by annjawn** [comment]
@zntfdr @mattdonnelly any help with this will be greatly appreciated.

**Comment by zntfdr** [comment]
Hi @annjawn,
the error you receive ``HTTP Status 420: Enhance Your Calm, Response: Exceeded connection limit for user`` indicates that you've requested that endpoint too many times in a short period of time. Almost every endpoint is rate limited, in your case you can confirm it [here](https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter) (there's another page where it explicitly states how many requests for each endpoint you can do in which amount of time...please try to find it in the documentation if this is something you step on often).

If you receive this error, I can assume you can establish the connection and everything is fine. 
If you don't see any tweet it might be because you're requesting to track terms that are not being tweeted _at the moment_ (**reminder**: Streaming APIs will send you tweets as they happen, you won't see any past tweet..unless it's a retweet).

Please try to use the streaming api with tracker ``["a"]`` for example, this way you should receive _a lot of_ tweets that have the letter a in them.

Lastly, what you see in https://github.com/mattdonnelly/Swifter/issues/97#issuecomment-350528839 might be just the small "_keep-alive_" packages that Twitter's servers will send to your device just to keep the connection alive (this is one big distinction between Streaming APIs and REST APIs, you can read about it [here](https://developer.twitter.com/en/docs/tutorials/consuming-streaming-data)).

**Comment by annjawn** [comment]
The 420 error was my mistake in the code and I fixed it. But with popular tracker terms the URLSessionDelegate is receiving data but the Swifter postTweetsFilter callback isn't getting fired. I even tried to track my other twitter account and tweeted a bunch of things but still the same issue. I am sure that I am receiving data but somewhere the callback chain seems to be broken.

**Comment by annjawn** [comment]
@zntfdr sorry, but I am truly stumped. I am not seeing any streaming at all.... I did debug and I noticed that the URLSession delegate is firing but as you said it might be just getting keep alives, but I have used a variety of track terms including `["a"]` but still not streaming. I see this `self.downloadProgressHandler?(data, totalBytesReceived, expectedContentLength, self.response)` being used in the delegate. Also, I have tried a few other steaming methods like the random sample one and it's the same case with that as well. Just a note, I am not using any of the FireHose/Decahose APIs since I am not a Twitter Enterprise member, so fr now I am using only the Public streaming methods.

**Comment by annjawn** [comment]
Alright, I think I am facing an ARC issue here. Inside the `jsonRequest` method. Some thread is breaking my strong reference and since the closure is safe by `weak self` the `guard` is returning which in turn is not calling the `handleStreamProgress` which is the root of the issue. I am not quite sure how solve this now. I tried moving the entire API call inside of my ViewController instead of using the singleton but I continue to get this issue. 

![image](https://user-images.githubusercontent.com/26977294/33817121-9d9fecee-ddf2-11e7-95a0-68c52d4d2761.png)

**Comment by zntfdr** [comment]
You're getting closer!

seems like your ``swifter`` instance is being deinitiated. Are you sure you're keeping it in memory?

**Comment by annjawn** [comment]
I am pretty sure I am maintaining strong reference of `swifter`and nowhere in the code de-initializing it.

**Comment by annjawn** [comment]
I even tried this, but its still deinitializing... (i put a print on `deinit`)

![image](https://user-images.githubusercontent.com/26977294/33818661-0184b4d0-ddfb-11e7-8801-894a2561f0cc.png)

**Comment by annjawn** [comment]
I even tried this, but its still deinitializing... (i put a print on `deinit`)

![image](https://user-images.githubusercontent.com/26977294/33818694-3589a376-ddfb-11e7-923e-3d8d926780e4.png)

**Comment by zntfdr** [comment]
Know we know what’s wrong. Is ‘connection’ a strong reference? Where is it?

What happens if ‘connection’ is declared globally?

________________________________

**Comment by annjawn** [comment]
It's a class property.

![image](https://user-images.githubusercontent.com/26977294/33818998-e451e188-ddfc-11e7-8cb0-9c42b152179f.png)

**Comment by annjawn** [comment]
Something very interesting.... I don't believe it's because of the scope of the `connection` variable (but I could be wrong). It's as if the highlight (in white box) line is causing the `deinit`. Look at the log.

![image](https://user-images.githubusercontent.com/26977294/33819189-fab31eb4-ddfd-11e7-983a-d77c5b3f0f52.png)

**Comment by zntfdr** [comment]
It’s an instance property. Please add the ‘class’ or ‘static’ modifier to make it a class property.

________________________________

**Comment by annjawn** [comment]
Ok my bad, that was an instance property, but using `static var connection: HTTPRequest?` also doesn't solve the problem. Same issue persists.

**Comment by zntfdr** [comment]
If ‘connection’ references strongly to the object it simply can’t be deinitiated. Is it possible that it turns into nil somewhere else? Please check.

________________________________

**Comment by annjawn** [comment]
Nope. This project is literally just one view controller that i created to play around with Swifter's streaming API. I don't see `connection` being set to nil anywhere. But just to be sure i changed the name to `static var conn: HTTPRequest?` and the problem persists.

**Comment by annjawn** [comment]
Just curious @zntfdr , is it working for you?

**Comment by zntfdr** [comment]
Please share here the view controller code so I can try (no screenshots).

________________________________

**Comment by annjawn** [comment]
Here you go

```
//
//  FeedVC.swift
//  TweetXpress-Development
//
//  Created by Anjan Biswas on 12/2/17.
//  Copyright © 2017 Ivyvine Apps. All rights reserved.
//

import UIKit
import TwitterKit
import Swifter

class FeedVC: UIViewController {

    @IBOutlet weak var feed: UITableView!
    let params = ["count": "50"]
    var tweets : [Any] = []
    var clientError : NSError?
    var prototypeCell: TWTRTweetTableViewCell?
    static var conn: HTTPRequest?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        feed.dataSource = self
        feed.delegate = self
        let tracker = ["Santa","Christmas"]
        
       //TwitterStreamHandler.instance.getSwifterClient() is a singleton method that returns an initialized Swifter objet. This is just one way I tried. I have also tried initializing a swifter object right here in the VC,and results were same so it doesn't matter
        
        FeedVC.conn = TwitterStreamHandler.instance.getSwifterClient().postTweetFilters(follow: nil, track: tracker, locations: nil, delimited: false, stallWarnings: true, filterLevel: nil, language: nil, progress: { json in
            
            print("ANN: JSON -", json)
            
        }, stallWarningHandler: { code, message, percentFull in
            
            print("ANN: Stall error ", message!)
        }, failure: { error in
            print("ANN: Error ", error.localizedDescription)
        })
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 20){
            print("ANN: stopping ")
            FeedVC.conn?.stop()
        }
        getUserHomeTimeline()
    }
    
}

//This below can be ignored... this is just creating a twitter timeline in a tableview using the https://api.twitter.com/1.1/statuses/home_timeline.json API

extension FeedVC: UITableViewDataSource, UITableViewDelegate, TWTRTweetViewDelegate{
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return tweets.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let tweet = tweets[indexPath.row] as! TWTRTweet
        let cell = feed.dequeueReusableCell(withIdentifier: "customtweetcell") as! CustomTweetCell
        cell.configureCell(with: tweet, likes: String(tweet.likeCount), retweets: String(tweet.retweetCount))
        return cell
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        let tweet = tweets[indexPath.row]

        let tweetheight = TWTRTweetTableViewCell.height(for: tweet as! TWTRTweet, style: .compact, width: self.view.frame.width, showingActions: false) + 30
        return tweetheight
    }
    
    fileprivate func getUserHomeTimeline(){
        
        let client = TWTRAPIClient(userID: "USE_YOUR_TWITTER_ID_HERE")
        let request = client.urlRequest(withMethod: "GET", url: "https://api.twitter.com/1.1/statuses/home_timeline.json", parameters: params, error: &clientError)
        
        client.sendTwitterRequest(request) { (response, data, connectionError) -> Void in
            if connectionError != nil {
                print("Error happened:", String.init(describing: connectionError))
                return
            }else{
                do {
                    let json = try JSONSerialization.jsonObject(with: data!, options: []) as? [Any]
                    self.tweets = TWTRTweet.tweets(withJSONArray: json)
                    self.feed.reloadData()
                } catch{
                    print("Error happened in JSON")
                    return
                }
            }
        }
        
    }
}

```

**Comment by zntfdr** [comment]
I just tried part of your code in the ``SwifterDemoiOS`` project and it works.

I've added this block of code at [this line](https://github.com/mattdonnelly/Swifter/blob/b5c86bcf625961ebc0d713d4a12a88d4fd073a55/SwifterDemoiOS/AuthViewController.swift#L92) :
````swift
      let tracker = ["Santa","Christmas"] //these terms should return a lot of tweets
      
      self.swifter.postTweetFilters(follow: nil, track: tracker, locations: nil, delimited: false, stallWarnings: true, filterLevel: nil, language: nil, progress: { json in
        
        print("ANN: JSON -", json)
        
      }, stallWarningHandler: { code, message, percentFull in
        
        print("ANN: Stall error ", message!)
      }, failure: { error in
        print("ANN: Error ", error.localizedDescription)
      })
````

I correctly receive all the 🎅  tweets (and keep receiving while writing this comment 😆 ). Please start from here and see what could be the issue for your code

**Comment by zntfdr** [comment]
I might have just find out the issue: ``swifter`` deinitializes because you don't keep any reference to it when you do:
````swift
        FeedVC.conn = TwitterStreamHandler.instance.getSwifterClient().postTweetFilters(follow: nil, track: tracker, locations: nil, delimited: false, stallWarnings: true, filterLevel: nil, language: nil, progress: { json in
        ...
````
please try to keep a reference around (of what is returned by ``TwitterStreamHandler.instance.getSwifterClient()``) and see how it works 😉

**Comment by annjawn** [comment]
Well, that's only one of the ways I have tried. In all my previous attempts I have kept a reference and it still didn't work. Also, I think the way we are initializing Swifter has something to do with it. I am using TwitterKit SDK to get active sessions with token and secret (no App only OAuth or ACAccount). The demo uses ACAccount, and it "working" only with that mode of initializing doesn't mean that it is working for how I am initializing it. I am increasingly inclined to believe it's a bug, I just need to point it out for you. Need some time. 😊

**Comment by annjawn** [comment]
Also, all the methods (singleton, directly in the VC etc) that I tried to initialize Swifter works perfectly fine for all the other non-streaming API methods and I get the correct responses back , but initializing Swifter with Consumer key, consumer secret, oauth token and secret is not working for the streaming methods.

**Comment by annjawn** [comment]
Yep... I did this

`let client = TwitterStreamHandler.instance.getSwifterClient()`

and then used `client` and it worked.
