### ISSUE TITLE
Post a tweet with a photo / media

### ISSUE THREAD

**Issue by rememberit1** [mattdonnelly/Swifter#227]
I'm trying to post a tweet with a photo but every time I try, i get an error "The operation couldn’t be completed. (SwifteriOS.SwifterError error 1.)"

My code looks like

```
var tweetMedia: [String: Any]?
//I then set tweetMedia to a UIImageView from the UIImagePickerControllerOriginalImage
let picForTwitterApi = tweetMedia![UIImagePickerControllerOriginalImage] as! UIImage
let image = UIImagePNGRepresentation(picForTwitterApi) as Data?
self.swifter?.postTweet(status: tweetText, media: image!, inReplyToStatusID: nil, coordinate: nil, placeID: nil, displayCoordinates: nil, trimUser: false, 
tweetMode: TweetMode.default, success: { json in self.alert(title: "Tweet PHOTO sent", message: "👍🏾")
            }, failure: failureHandler)

```
But it does not work, i even tried

```
self.swifter?.postMedia(image!, additionalOwners: nil, success: { json in
                print(json)
```

instead, still no success. When I post a regular vanilla tweet like 
```
self.swifter?.postTweet(status: tweetText, inReplyToStatusID: nil, trimUser: false, tweetMode: TweetMode.default, success: { json in
                print(json).....
```

Everything works perfectly fine, I only have problems when I try to post a photo. Please help. Thanks in advance

**Comment by meteochu** [comment]
Sorry I didn't respond to this earlier. Can you cast the error as a `SwifterError` type and see what the error description is.

```swift
..., failure: { error in
  if let error = error as? SwifterError {
    print(error.message)
  }
})
```

**Comment by peihsendoyle** [comment]
we got 403. Forbidden

**Comment by peihsendoyle** [comment]
after authorize the app, we got "HTTP Status 400: Bad Request, Response: {"request":"\/1.1\/media\/upload.json","error":"media type unrecognized."}"

I'm sending an .mov file. did twitter support mov?

**Comment by rememberit1** [comment]
I found the solution. The picture must be small. Even smaller than 5mb the documentation suggest. I used an image that was only 100KB and it worked. If I want to post a larger image/video (even just one picture) you have to use the chunked media post ability. I haven't tested the chunked media posting ability however. Just saying that based on the documentation. 
My swift code to post a tweet with a pic:
`self.swifter?.postMedia(image!, additionalOwners: nil, success: { json in
                let mediaIdString = json["media_id_string"].string
                print(json)
                
                if (self.tweetID != nil){
                    tweetText = "@\(self.replyUsername!) " + tweetText
                }
                
                self.swifter?.postTweet(status: tweetText, inReplyToStatusID: self.tweetID, coordinate: nil, placeID: nil, displayCoordinates: false, trimUser: false, mediaIDs: [mediaIdString!], attachmentURL: nil, tweetMode: TweetMode.default, success: { json in
                    print(json)
                }, failure: failureHandler)
                
            }, failure: failureHandler)`

**Comment by rememberit1** [comment]
Let me know if you find a better solution

**Comment by msebgf** [comment]
> after authorize the app, we got "HTTP Status 400: Bad Request, Response: {"request":"/1.1/media/upload.json","error":"media type unrecognized."}"
> 
> I'm sending an .mov file. did twitter support mov?

How do you authorize the app? I'm getting the 403 error

**Comment by rememberit1** [comment]
> > after authorize the app, we got "HTTP Status 400: Bad Request, Response: {"request":"/1.1/media/upload.json","error":"media type unrecognized."}"
> > I'm sending an .mov file. did twitter support mov?
> 
> How do you authorize the app? I'm getting the 403 error

look at these pages https://stackoverflow.com/questions/51413915/new-twitter-update-authentication and https://stackoverflow.com/questions/28005919/how-to-authorize-twitter-with-swifter/29326470

**Comment by meteochu** [comment]
This problem seems to be solved, so I'm closing the issue. If you are still running into more problems, please feel free to comment or create a new issue.
