### ISSUE TITLE
Getting a 401 on direct_messages/events/new.json

### ISSUE THREAD

**Issue by WillBishop** [mattdonnelly/Swifter#232]
Hey, 

I'm trying to move to the new APIs for Twitter, as the ones I use are being removed in 2 days.

I can post to any URL on Twitter with seemingly no issues, however upon trying to use the new direct_messages/events/new.json, I'm getting a 401 error.

 ```
public func sendDirectMessage(to userTag: UserTag, text: String, success: SuccessHandler? = nil, failure: FailureHandler? = nil) {
		
        let path = "direct_messages/events/new.json"

        var parameters = Dictionary<String, Any>()
		var event = Dictionary<String, Any>()
		var message_create = Dictionary<String, Any>()
		var message_data = Dictionary<String, Any>()
		var target = Dictionary<String, Any>()
		
		
		target["recipient_id"] = userTag.value
		
		message_data["text"] = text
		
		message_create["message_data"] = message_data
		message_create["target"] = target

		event["type"] = "message_create"
		event["message_create"] = message_create
		parameters["event"] = event
		
		//All of the above producess:
//		{
//			"event": {
//				"type": "message_create",
//				"message_create": {
//					"target": {
//						"recipient_id": "706321333915770880"
//					},
//					"message_data": {
//						"text": "Hello"
//					}
//				}
//			}
//		}
		//Perfectly matching https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-event

        self.postJSON(path: path, baseURL: .api, parameters: parameters, success: { json, _ in success?(json) }, failure: failure)
    }
```

The above returns:
`SwifterError(message: "HTTP Status 401: Unauthorized, Response: {\"errors\":[{\"code\":32,\"message\":\"Could not authenticate you.\"}]}", kind: urlResponseError(status: 401, headers: [AnyHashable("Content-Type"): application/json; charset=utf-8, AnyHashable("x-response-time"): 167, AnyHashable("Content-Encoding"): gzip, AnyHashable("x-connection-hash"): 1ba589a7fd7ffb7c6fc97418fa87e9e5, AnyHashable("Server"): tsa_l, AnyHashable("Strict-Transport-Security"): max-age=631138519, AnyHashable("x-tsa-request-body-time"): 2, AnyHashable("Content-Length"): 89, AnyHashable("Date"): Wed, 13 Jun 2018 12:06:24 GMT, AnyHashable("Set-Cookie"): personalization_id="v1_/MneNIGognq9RbaztuGSRQ=="; Expires=Fri, 12 Jun 2020 12:06:24 GMT; Path=/; Domain=.twitter.com, guest_id=v1%3A152889158471096841; Expires=Fri, 12 Jun 2020 12:06:24 GMT; Path=/; Domain=.twitter.com], errorCode: 32)`

I'm fairly new to Swifter, so apologies if this is a simple question. Appreciate any help.

**Comment by WillBishop** [comment]
You’re right that it requires additional permissions, but I have granted them.

I was really hoping that’d fix it, let me know if you think of anything else.

**Comment by WillBishop** [comment]
@meteochu I can confirm that during the authorization phase Twitter does state that the application will have access to the "Direct Messages".

Other "Event" APIs (such as listing direct messages) work just fine, it's just sending that gives a 401.

**Comment by WillBishop** [comment]
Can confirm this issue exists in the SwifterDemoiOS application

**Comment by meteochu** [comment]
Did some investigations and found the following results:

- Old (Deprecated) API for sending DMs use POST requests with query string to specify recipient and text
- New (Events) API uses POST requests that attaches the payload as an HTTPBody of the URL request.

We'll need to add support for that in order for this API to work because your current code would just add that payload directly append the URL with the query string for the payload

**Comment by meteochu** [comment]
Have updated Swifter just now to support the new DM APIs, this issue will now be closed as it is resolved.
