### ISSUE TITLE
SwifterDemoiOS Error 1?

### ISSUE THREAD

**Issue by tatters1979** [mattdonnelly/Swifter#233]
Hi, 

I just downloaded the git and tried to launch the SwifterDemoiOS but Error 1 appears upon hitting the Login with Twitter button?

    @IBAction func didTouchUpInsideLoginButton(_ sender: AnyObject) {
        let failureHandler: (Error) -> Void = { error in
            self.alert(title: "Error???", message: error.localizedDescription)
            
        }

I replaced the key and secret with my own but no luck?

Thanks

**Comment by meteochu** [comment]
Twitter recently made changes to their app callback url requirements. All apps are now required to whitelist their callback Url in the applications page, otherwise the REST API will return an error.

**Comment by tatters1979** [comment]
Hi meteochu,

Thanks, I've read the documentation on the link you provided. I've added a valid url to the callback field on my Twitter app settings page but are there any changes required in the SwifterDemoiOS code (maybe in info.plist)? I'm still getting the same error?

Thanks

**Comment by meteochu** [comment]
To test out if SwifterDemoiOS works, just plug in `swifter://` as a whitelisted callback URL on the app settings of the access token you replaced Swifter's with. To have the default one to work, we need @mattdonnelly to add `swifter://` as a whitelisted callback since he is the one who owns that access token/secret.

**Comment by tatters1979** [comment]
I created a totally new app and used the key & secret from that with swifter:// as the call back....it's now working. Thanks again.

**Comment by meteochu** [comment]
This issue is now resolved and will be closed.
