### ISSUE TITLE
Cocopods is on version 1.4.1

### ISSUE THREAD

**Issue by robertodias180** [mattdonnelly/Swifter#236]
@mattdonnelly can you please update the pod?

**Comment by meteochu** [comment]
Swifter's name conflicts with another Pod (also named Swifter) so we can't really publish it under CocoaPods Specs repo unless @mattdonnelly wants to change the name. You can specify the Pod's git manually which will fetch this repo. (The version should be 2.2.1)

**Comment by robertodias180** [comment]
@meteochu I am using it with the git link, but I think that we should fix the name issue 😄
