### ISSUE TITLE
Question: Get the user email

### ISSUE THREAD

**Issue by robertodias180** [mattdonnelly/Swifter#237]
Is there any way to get the user email?

**Comment by meteochu** [comment]
Not through the normal API; from what I recall, you must request elevated permission from Twitter for information such as email.

**Comment by robertodias180** [comment]
@meteochu You need the permission and then you can add it as a parameter `parameters["include_email"]` on the request `verifyAccountCredentials`.
I ended up creating a fork because I was needing that. If you guys want I can make a PR.

**Comment by meteochu** [comment]
Oh, I didn't realize that. Please do!

**Comment by robertodias180** [comment]
@meteochu  check https://github.com/mattdonnelly/Swifter/pull/238
