### ISSUE TITLE
New Twitter update authentication

### ISSUE THREAD

**Issue by rememberit1** [mattdonnelly/Swifter#241]
As you know, Twitter upgraded everything dealing with authentication. My app using this your library was working fine before this update. I even ran your demo app by itself and it works fine. But now all of a sudden I am unable to login to my app. I regenerated the tokens as secret keys in apps.twitter.com. In my app when I call  swifter.authorize(..., it starts to authenticate and goes to the twitter login page and right after I click the login button it shows me an error in a Safari window "Safari cannot open the page because the server cannot be found". In my apps.twitter.com In the setting section, the first callback url I have is http://MyTweeter ...It wants to me to add another callback, idk why/what so I just added http://google.com. What did you put as your callback urls in your twitter dashboard page. Where did I go wrong? Thank you.

**Comment by meteochu** [comment]
You need to have your app's callback url set up on Twitter's developer portal. Suppose you setup your app's callback to be at: `myapp://login-success`, then on Twitter's dev portal, you need to add the callback url: `myapp://`

**Comment by rememberit1** [comment]
this answer does not work in the settings section of apps.twitter.com. if the url starts off with anything other http or https and then I click update settings, I get the error "The client application failed validation: Not a valid callback URL format."

**Comment by meteochu** [comment]
Yeah, you have to make sure you don't type after anything the `://` Only the first part.

**Comment by rememberit1** [comment]
It works. Thanks, your a life saver!
