### ISSUE TITLE
How to tweet without authorizing each time?

### ISSUE THREAD

**Issue by chrisgreg** [mattdonnelly/Swifter#244]
I've managed to get the app to login but I can only run the postTweet function inside the success handler for logging in?

I want to store the oAuth session and use it throughout the app.

I assumed I could store the accessToken returned from the successful callback and using it but the postTweet function doesn't accept a token parameter.

**Comment by meteochu** [comment]
The authentication step should only ever be needed once. Once you store the access token (and access token secret) returned from the authentication, you can create another Swifter instance with the tokens themselves using the following initializer:

```swift
 public init(consumerKey: String, consumerSecret: String, oauthToken: String, oauthTokenSecret: String)
```

**Comment by chrisgreg** [comment]
Gotcha! Thanks
