### ISSUE TITLE
Swifter on server side (Mac) hangs

### ISSUE THREAD

**Issue by EricWVGG** [mattdonnelly/Swifter#248]
I am attempting to use Swifter in conjunction with the Vapor 3 server side web framework. It builds fine, but any attempt to use it just hangs. Even in test environment, no errors, just eerie stillness. 

I am doing the connection in a background thread since Vapor doesn't allow blocking on the main thread, could this be causing any issues?
```swift
self.twitter = Swifter(consumerKey: key!, consumerSecret: secret!)
let async = context.container.eventLoop.newPromise(Void.self)
DispatchQueue.global(qos: .background).async {
    print("Marco?")
    let callback = URL(string: "https://asdf.horse/twitter")
    self.twitter.authorize(withCallback: callback!, success: { accessToken, response in
        print("Polo! (this never happens)")
        print(response)
        async.succeed(result: ())
    }, failure: { error in
        print("This never happens either.")
        async.fail(error: error)
    })
}
return async.futureResult.flatMap { _ -> Future<Void> in
    // go on to do some stuff like a users/search
}
```

**Comment by EricWVGG** [comment]
… This appears to be because Swifter is doing its own async on the main thread, which Vapor doesn't like at all. Changing `SwifterHTTPRequest.swift` line 168 to…
```
DispatchQueue.global(qos: .background).async {
```
… causes it to go a bit further, but now Swifter isn't picking up the success/fail message (I think?)

At any rate, my impression is that Swifter is intended to be more of a client library and server side, so I may have to roll out a different solution. Closing this issue, but please let me know if I'm wrong and there's a solution to be found.

**Comment by joshwolff1** [comment]
Having same issue with iOS
