### ISSUE TITLE
how to user getBlockedUsers

### ISSUE THREAD

**Issue by rememberit1** [mattdonnelly/Swifter#257]
I'm trying to user the getBlockedUsers function but nothing happens when i do it (or I am doing it wrong). This is how i call the function:
`swifter?.getBlockedUsers(includeEntities: false, skipStatus: true, cursor: "", success: mySuccess as? Swifter.CursorSuccessHandler, failure: failureHandler)`
and this is what my success handler looks like:

```
let mySuccess: (JSON, String, String) -> Void = { someJson, someString, anotherString in print("some array: ", someJson)
print("some array: ", someString)
print("some array: ", anotherString)}
```
After this....nothing is printed to the console when i go to user that has people blocked.

**Comment by meteochu** [comment]
The type for your success handler does not match `Swifter.CursorSuccessHandler` and so when you optionally cast the object `mySuccess as? Swifter.CursorSuccessHandler`, it returns `nil` and so has no success handler (hence, why nothing is printed)
