### ISSUE TITLE
Swifter is not reacting

### ISSUE THREAD

**Issue by kzahedi** [mattdonnelly/Swifter#260]
Hi,

I am new to swift and new to swifter and I am currently trying to write a command line tool to access my twitter feed.

I am using the following code with xcode 10, swift 4.2 and swifter 2.2.2 (installed via swift package manager):

`
let failureHandler: (Error) -> Void = {
    print("failure")
    print($0.localizedDescription)
}

var swifter = Swifter(consumerKey: cfg.apiKey, consumerSecret: cfg.apiSecretKey, oauthToken: cfg.accessToken, oauthTokenSecret: cfg.accessTokenSecret)

swifter.getHomeTimeline(success: { json in
  print(json)
}, failure: failureHandler)`

The keys are set correctly, I have verified that.

I traced the function call all the way back to the get function in OAuth (line 55), which seems to be called, but neither my success nor my failure functions are called. url.absoluteUrl returns https://api.twitter.com/1.1/statuses/home_timeline.json.

Any help is highly appreciated.

Best,
Keyan

**Comment by meteochu** [comment]
That's very odd; I've just tried it with my own keys and tokens and it worked fine. Something *should* at least print and I can't really tell what's wrong.

**Comment by kzahedi** [comment]
I have created a minimal example:

`
import Foundation
import Swifter

let cfg = readConfig(filename: configFile) // reads the tokens and api keys into a struct

let group = DispatchGroup()
group.enter()

var swifter = Swifter(consumerKey: cfg!.apiKey, consumerSecret: cfg!.apiSecret, oauthToken: cfg!.accessToken, oauthTokenSecret: cfg!.accessTokenSecret)

swifter.getHomeTimeline(count: 50, success: { json in
   print(json)
    group.leave()
}, failure: { error in
    print(error)
    group.leave()
})

print("waiting")
group.wait()
print("done waiting")
`

The code never reaches "done waiting" and no jsons are printed. I am using Swifter in a command line tool, i.e., in a project that I created using

`swift package init --type executable`

then adding Swifter to the Packages.swift, etc.

**Comment by meteochu** [comment]
Ah, I see what you're doing. Since you're creating running Swifter in a command line utility (using SwiftPM), you need to have a runloop, otherwise you cannot have asynchronous calls. You need to add the following to a line before you wait so that the program doesn't just end when it calls `wait` 

```swift
RunLoop.main.run()
```

**Comment by kzahedi** [comment]
Thank you very much! This solved my problem!

**Comment by meteochu** [comment]
I'm glad I could help! Closing this issue now.
