### ISSUE TITLE
How do I change a String into a UserTag?

### ISSUE THREAD

**Issue by chadbrochill317** [mattdonnelly/Swifter#262]
Hello, 
I am receiving this issue:
Cannot convert value of type 'String' to expected argument type 'UserTag'

I am using a string as the UserTag, and was just wondering, how I can get it to the UserTag enum form. 

Thanks

**Comment by meteochu** [comment]
A `UserTag` is an `enum` to specify between a user_id or a screen_name; you can read more about it.
You can use do either `UserTag.screenName("username")` or `UserTag.id("xxxxxxxxx")`

Read more about it in [SwifterTag.swift](../blob/master/Sources/SwifterTag.swift)

**Comment by chadbrochill317** [comment]
Thank you chief
