### ISSUE TITLE
Getting user login credentials from Twitter app

### ISSUE THREAD

**Issue by lev-kusanagi** [mattdonnelly/Swifter#267]
Hi,

Currently the login has to happen either in-app or in Safari, it's not clear from the docs if one can get the user login credentials from the Twitter app itself. (Twitter Kit can do that).

Is this possible? If not, how could this be implemented?

Thank you!

**Comment by meteochu** [comment]
IIRC, TwitterKit was discontinued some time last year. But also, I don't think logging in via the Twitter app is open for developers?
