### ISSUE TITLE
Can't find Swifter with pod search

### ISSUE THREAD

**Issue by lev-kusanagi** [mattdonnelly/Swifter#270]
Neither the command pod search swifter or a search on cocoapods.org show Swifter as one of the results.

I can install it with the git option in the podfile but it would be great to have it in cocoapods too for pod install swifter.

Thanks!

**Comment by gintechsystems** [comment]
This works and finds it for me:

`pod 'Swifter', :git => 'https://github.com/mattdonnelly/Swifter.git'`

**Comment by Mekkawy** [comment]
@gintechsystems 
CocoaPods could not find compatible versions for pod "Swifter":
  In Podfile:
    Swifter (from `https://github.com/mattdonnelly/Swifter.git`)

**Comment by gintechsystems** [comment]
What version of Swift are you using? If you look in the podspec for that git project, it only works with Swift 5.0 anymore.

**Comment by gintechsystems** [comment]
I think if someone updates the pod spec to have other versions than just 5.0, it should still work with older versions.

**Comment by meteochu** [comment]
This problem seems to be solved, so I'm closing the issue. If you are still running into more problems, please feel free to comment or create a new issue.
