### ISSUE TITLE
Alternative to TwitterKit? for Log in with twitter.

### ISSUE THREAD

**Issue by smhk** [mattdonnelly/Swifter#276]
Hey guys, 

if you want to use _"Log in with twitter"_ in an app,

TwitterKit is discontinued (example: [twitter blog on that](https://blog.twitter.com/developer/en_us/topics/tools/2018/discontinuing-support-for-twitter-kit-sdk.html) )

In fact, is this fine repo an alternative to using TwitterKit?  Thanks for the explanation.

Twitter's doco is super-confusing because it says in a number of places they "offer" iOS _"Log in with Twitter"_, but, they never give any info on how to do it with iOS or how they want it done with iOS!  Thanks, and Totoro says thanks too :)

**Comment by meteochu** [comment]
Well, Swifter is an all-rounded Twitter SDK client for iOS. If you're looking to fetch specific data via Twitter API, then yeah, this is a great alternative to using it.

**Comment by smhk** [comment]
thanks for your time, good one
