### ISSUE TITLE
2 tabs was opened at safali when called authorize function in Xcode11 beta.

### ISSUE THREAD

**Issue by kumanmushi** [mattdonnelly/Swifter#277]
2 tabs was opened at Safali when called iOS authorize function in Xcode11 beta.
First tab is `https://api.twitter.com/oauth/authorize?oauth_token=[Token]`
Second tab is searched `oauth_token=[Token]`.
2tabs was random displayed.

**Comment by meteochu** [comment]
Interesting issue. It seems like this is caused by opening URL created with relative urls. This issue has been fixed in d8ab61e.
