### ISSUE TITLE
Commit f5a8413 fails to build

### ISSUE THREAD

**Issue by mvalentiner** [mattdonnelly/Swifter#280]
I just pulled commit f5a8413, Support Single Sign-On. (#271), and am getting an error on AuthViewController.swift, line 43: "Use of unresolved identifier 'authorizeMode'".
Indeed, authorizeMode is undefined.

**Comment by meteochu** [comment]
Sorry about that, seems like the last changes had a typo in the variable name that wasn't caught when I approved the PR. I've fixed it now.
