### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by uniqart** [mattdonnelly/Swifter#281]
I use Xcode 11 and I keep getting the following error:

CpResource /Users/mj/Library/Developer/Xcode/DerivedData/Twittermenti-cyloobwyiknqyohegdgtnollxycr/Build/Products/Debug-iphonesimulator/SwifterDemoiOS.app /Users/mj/Library/Developer/Xcode/DerivedData/Twittermenti-cyloobwyiknqyohegdgtnollxycr/Build/Products/Debug-iphonesimulator/Twittermenti.app/SwifterDemoiOS.app (in target 'Twittermenti' from project 'Twittermenti')
    cd /Users/mj/Documents/Training/iOS/Twittermenti-iOS12
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/mj/Library/Developer/Xcode/DerivedData/Twittermenti-cyloobwyiknqyohegdgtnollxycr/Build/Products/Debug-iphonesimulator/SwifterDemoiOS.app /Users/mj/Library/Developer/Xcode/DerivedData/Twittermenti-cyloobwyiknqyohegdgtnollxycr/Build/Products/Debug-iphonesimulator/Twittermenti.app

error: /Users/mj/Library/Developer/Xcode/DerivedData/Twittermenti-cyloobwyiknqyohegdgtnollxycr/Build/Products/Debug-iphonesimulator/SwifterDemoiOS.app: No such file or directory (in target 'Twittermenti' from project 'Twittermenti')

**Comment by meteochu** [comment]
How are you using the Swifter with your project?

**Comment by uniqart** [comment]
All good, I have out the project file into my project which was right but the problem was (I think)  that I had the project in Swift 4 which wasn’t running correctly on Xcode 11 and I wasn’t able to migrate due to the error. So I delete Swifter, migrated to Swift 5, put Swifter back into the project and integrated the framework. After that everything worked perfectly.

Thanks for your quick follow up. Great Framework!

**Comment by shekhar0810** [comment]
> All good, I have out the project file into my project which was right but the problem was (I think) that I had the project in Swift 4 which wasn’t running correctly on Xcode 11 and I wasn’t able to migrate due to the error. So I delete Swifter, migrated to Swift 5, put Swifter back into the project and integrated the framework. After that everything worked perfectly.
> 
> Thanks for your quick follow up. Great Framework!

I also had the same issue and it worked fine after following the steps mentioned by you. Thank you
