### ISSUE TITLE
Transitioning from TwitterKit to Swifter

### ISSUE THREAD

**Issue by TheApApp** [mattdonnelly/Swifter#285]
I have an app I wrote years ago with TwitterKit, and am looking to transition to Swifter now that TwitterKit is no longer supported.  However, I am not finding any good resources or sample code for writing a simple Post a Tweet using Swifter.  I know how to create the tweet, but nothing seems to happen.  It appears that Swifter requires usage of a callbackURL.  Can you post a wiki or simple sample code for posting a static tweet using Swifter?

**Comment by smhk** [comment]
@TheApApp - (don't you hate transitioning!) ...  I don't know if it helps, but the demo app (included right here) does that very easily and is fully exampled.  Hope it helps!

**Comment by TheApApp** [comment]
Thanks will dig thru that code.

**Comment by meteochu** [comment]
As mentioned above, the demo app in the project should be sufficient to getting a full flow on logging in and getting tweets. Closing this issue now, but feel free to comment if you have additional questions.
