### ISSUE TITLE
Error and crash on startup (13.3.1 beta)

### ISSUE THREAD

**Issue by DimSar01** [mattdonnelly/Swifter#287]
I'm relatively new to development firstly. Anyway, I have made a custom app for my Twitter account to post tweets which works fine on 13.3. However, when I tried running it on 13.3.1 beta (17D5026c), the app crashes on startup with the error shown in the screenshot
<img width="1440" alt="Στιγμιότυπο 2019-12-31, 3 20 54 μμ" src="https://user-images.githubusercontent.com/58777168/71623608-88740a00-2be6-11ea-88e6-312a2522f648.png">

**Comment by DimSar01** [comment]
The error still persists with beta 2 (17D5044a) and Xcode 11.3.1

**Comment by meteochu** [comment]
How are you configuring Swifter in your project? It seems more like an Xcode issue with not copying the framework to the right location than anything. Does this still reproduce?

**Comment by DimSar01** [comment]
No no, it was fixed with the 13.4 beta and Xcode 11.4. Thanks:)
