### ISSUE TITLE
 Do I have to use the master branch to use SSO?

### ISSUE THREAD

**Issue by assaulter** [mattdonnelly/Swifter#288]
I want to use the features included in this commit. https://github.com/mattdonnelly/Swifter/pull/271
But I think this commit has not been released since it was merged.

Are you planning to release a new version?
thanks.

**Comment by meteochu** [comment]
Apologies. I haven't been able to keep up with changes since I've been occupied with some other commitments. Once I go through the queue of changes, I'll release a new version with all the new changes.
