### ISSUE TITLE
Authorization Error (com.apple.accounts error 7)

### ISSUE THREAD

**Issue by sukhpreetdhatt** [mattdonnelly/Swifter#292]
Hi, I tried to run iOS demo on simulator, it allows to authenticate using `.browser `and `.sso` Authorization Mode but it doesn't work with`.acaccount`.  Its showing popup with Error 

> "The operation couldn't be completed(com.apple.accounts error 7)

I'm not sure about this error, if anyone knows what is it please let me know.

**Comment by noahkamara** [comment]
ACAccounts for Twitter are deprecated. Thats probably the issue.
