### ISSUE TITLE
app authorize does not supply oauthTokenSecret or userId?

### ISSUE THREAD

**Issue by smhk** [mattdonnelly/Swifter#298]
When I `swifter.authorize(withCallback` I perfectly get

```
token?.key >1152600219026149378-GfLTRzjjkrxxxxxxxxxxyyyyyyyyyy< 
token?.secret >1152600219026149378-GfLTRzjjkrxxxxxxxxxxyyyyyyyyyy< 
token?.userID >115260021xxxxxxxxxx<
```

which is amazing.  But, when I `swifter.authorizeAppOnly`  I get

```
token?.key >1152600219026149378-GfLTRzjjkrxxxxxxxxxxyyyyyyyyyy< 
token?.secret >null< 
token?.userID >null<
```

Help!  

I did try both true/false appOnly argument in init.

What could it be ?

**Comment by meteochu** [comment]
We didn't used to retrieve the userID when performing app only authorization. It was added in the following change that I merged not long ago https://github.com/mattdonnelly/Swifter/commit/754cbd03b0c6bc8e59d3f6985cee90e0cf7226e5

Closing as completed.
