### ISSUE TITLE
ACAccountStore was deprecated in macOS 10.13 use Twitter SDK instead

### ISSUE THREAD

**Issue by TheApApp** [mattdonnelly/Swifter#303]
I am working on a SwiftUI/Combine app with Swifter.  When trying to get the demo code to work, I get the following error: 

`.swift:60:87: 'ACAccountTypeIdentifierTwitter' was deprecated in macOS 10.13: Use Twitter SDK instead`

Is there a recommended setup for this?

**Comment by TheApApp** [comment]
the TwitterKit API recommendation seems to also be deprecated by twitter

**Comment by meteochu** [comment]
ACAccountStore was deprecated a while ago, it's kept there for binary compatibility since Swifter is supported on older versions that still support ACAccountStore. I'll make a change to note the deprecation though.

**Comment by meteochu** [comment]
Marked the ACAccount initializers as deprecated in Swifter and also updated the sample project in
https://github.com/mattdonnelly/Swifter/commit/a08088f7b74e696f5bcb1be7a4e2f5a43a9cba85
