### ISSUE TITLE
Does it support Mac Catalyst?

### ISSUE THREAD

**Issue by Silent404** [mattdonnelly/Swifter#304]
I can't log in with Mac Catalyst

**Comment by meteochu** [comment]
Can you provide more information? How are you trying logging in? I enabled the Catalyst checkbox on the sample project in Swifter.xcodeproj and I'm able to login just fine. Presenting a SFSafariViewController seems to directly switch to your Mac browser directly and move the login flow there, which will bounce back to the Catalyst app once it's done.

**Comment by Silent404** [comment]
sorry
It was my code mistake
