### ISSUE TITLE
Support for the next Twitter API version

### ISSUE THREAD

**Issue by andypiper** [mattdonnelly/Swifter#308]
Hi friends! Andy here, from Twitter Developer Relations :-)

Swifter is basically one of the only libraries available that helps Swift developers to access the Twitter API (I've also used OAuthSwift, which is also very neat). After WWDC this week, I'm particularly excited to see what we can do together! Swift and SwiftUI are very nice platforms and frameworks.

Do you have any plans to support the [Twitter Developer Labs](https://developer.twitter.com/en/labs) endpoints and fields? Although the paths may change at release, you can expect the overall pattern to be very similar, since we've been in pilot with this new version for some time.

Feel free to Tweet me @andypiper, or chat with us on the [developer forums](https://twittercommunity.com/c/labs/57) if you'd like to learn more. Not long now! We will not be replacing everything you're familiar with at launch, but we think a lot of developers will be interested in the new features (topic context annotations, pinned Tweets, poll data, etc etc).

**Comment by meteochu** [comment]
Hi there, (also) Andy here :)

I have been semi-actively maintaining Swifter for the past couple of years but have not been able to do that much given my other previous commitments. I should be more free to work on this framework over the next couple of months and would love to expand Swifter's capabilities with new Twitter APIs. Is there a quick summary on the differences between the currently available v1.1 APIs and the ones from Twitter Developer Labs? I assume these are more related to improved end-points and that the core API flow should remain intact right?

**Comment by andypiper** [comment]
Great, thanks for asking about this, and for maintaining Swifter!

The core auth flow remains the same, but the data formats are very different, and the API is much more granular, supporting the concept of querying individual fields. The high level doc on the differences is [here](https://developer.twitter.com/en/docs/labs/overview/whats-new) (ignore "Formats", as they were replaced by "Fields" in Labs v2, and that's what I'd expect to see become released in the future). There are some really nice features in Labs, such as access to pinned Tweets, topic annotations, and poll data.

Overall, there will be a period of parallel running between v1.1 and the next endpoints, as we will be releasing updated endpoints in waves over time.

**Comment by meteochu** [comment]
I will check it out some time when I get the chance. Thanks for the info.

**Comment by lev-kusanagi** [comment]
@andypiper thanks for posting, it's great and encouraging to see you drop by! Looking forward to working with the new API and Swifter. @meteochu I'd love to help, whenever I can!

**Comment by Devecstatic** [comment]
Hi, is there any update on when this will be happening or any developmental branch to be up to date on it?

**Comment by meteochu** [comment]
Unfortunately, I got too busy shipping some other projects and did not end up finding time to do it yet. I'm still trying to find time but I cannot promise anything so if anyone wants to start on it, be my guest.

**Comment by Devecstatic** [comment]
Alight! Ill take a look into it and try to see what I can do. Thank you for the response!

**Comment by lev-kusanagi** [comment]
@Devecstatic happy to collaborate. have you started on this?

**Comment by Devecstatic** [comment]
> @Devecstatic happy to collaborate. have you started on this?

Not yet @lev-kusanagi, but I plan on starting next week!

**Comment by Srijan1998** [comment]
@lev-kusanagi I see you have started work on this. Can I collaborate?

**Comment by lk251** [comment]
@Srijan1998 yes sir!

**Comment by lk251** [comment]
@Srijan1998 search v2 is halfway done (see my branch experimental-master), I'll try to finish it soon, would you like to take a first stab at v2 timelines?

**Comment by lk251** [comment]
@meteochu @Kyome22 @EthanLipnik got basic v2 search to work, looking to make ASWebAuthenticationSession based authentication SwiftUI compatible, any help on how to get started would be appreciated. Thank you!

**Comment by EthanLipnik** [comment]
I’ll try to help out today!

– Ethan Lipnik

**Comment by Srijan1998** [comment]
@lk251 check out my fork https://github.com/Srijan1998/Swifter
I had replaced quite a few endpoints.

**Comment by lk251** [comment]
@EthanLipnik @Srijan1998 awesome!! BTW have you guys figured out how to use ASWebAuthenticationSession in SwiftUI? Any help would be welcome, I'm stuck using the deprecated authentication for now. cc @mattdonnelly @meteochu

**Comment by lk251** [comment]
@Srijan1998 I'm adding new functions instead of modifying existing ones, so the user can use both v1.1 and v2 endpoints.
BTW I think I had to change pagination_token to next_token in v2 search, even though (if I'm not mistaken) the docs said to use pagination_token

**Comment by aehlke** [comment]
What are people using these days?
