### ISSUE TITLE
Xcode 12 beta3，a problem encountered when archived

### ISSUE THREAD

**Issue by jyrnan** [mattdonnelly/Swifter#311]
Hi! I am learning SwiftUI to rebuild my app, a small twitter client. 
My coding environment is Xcode 12 beta3 on Mac OS Big Sur. 
My app had been released for testFlight for several version.
Now my app can be build and run in simulator or my own iPhone , But when I want to archive my work for testFlight, a problem occurred.
Showing Recent Messages
"Undefined symbol: type metadata for Swift._StringObject.Variant"

Is there any bug in my code or something changed in Swifter, or caused by Xcode beta? 

Thanks!

Full information below:
"Ld /Users/jyrnan/Library/Developer/Xcode/DerivedData/FetchMeeBySwiftUI-dqsbshiaztjeorgjkelrhfgkzkes/Build/Intermediates.noindex/ArchiveIntermediates/FetchMeeBySwiftUI/IntermediateBuildFilesPath/Swifter.build/Release-iphoneos/SwifteriOS.build/Objects-normal/armv7/Binary/SwifteriOS normal armv7 (in target 'SwifteriOS' from project 'Swifter')
    cd /Users/jyrnan/Developer/Swifter
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target armv7-apple-ios10.0 -dynamiclib -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.0.sdk -L/Users/jyrnan/Library/Developer/Xcode/DerivedData/FetchMeeBySwiftUI-dqsbshiaztjeorgjkelrhfgkzkes/Build/Intermediates.noindex/ArchiveIntermediates/FetchMeeBySwiftUI/BuildProductsPath/Release-iphoneos -F/Users/jyrnan/Library/Developer/Xcode/DerivedData/FetchMeeBySwiftUI-dqsbshiaztjeorgjkelrhfgkzkes/Build/Intermediates.noindex/ArchiveIntermediates/FetchMeeBySwiftUI/BuildProductsPath/Release-iphoneos -filelist /Users/jyrnan/Library/Developer/Xcode/DerivedData/FetchMeeBySwiftUI-dqsbshiaztjeorgjkelrhfgkzkes/Build/Intermediates.noindex/ArchiveIntermediates/FetchMeeBySwiftUI/IntermediateBuildFilesPath/Swifter.build/Release-iphoneos/SwifteriOS.build/Objects-normal/armv7/SwifteriOS.LinkFileList -install_name @rpath/SwifteriOS.framework/SwifteriOS -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/jyrnan/Library/Developer/Xcode/DerivedData/FetchMeeBySwiftUI-dqsbshiaztjeorgjkelrhfgkzkes/Build/Intermediates.noindex/ArchiveIntermediates/FetchMeeBySwiftUI/IntermediateBuildFilesPath/Swifter.build/Release-iphoneos/SwifteriOS.build/Objects-normal/armv7/SwifteriOS_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/jyrnan/Library/Developer/Xcode/DerivedData/FetchMeeBySwiftUI-dqsbshiaztjeorgjkelrhfgkzkes/Build/Intermediates.noindex/ArchiveIntermediates/FetchMeeBySwiftUI/BuildProductsPath/Release-iphoneos -fobjc-link-runtime -L/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/jyrnan/Library/Developer/Xcode/DerivedData/FetchMeeBySwiftUI-dqsbshiaztjeorgjkelrhfgkzkes/Build/Intermediates.noindex/ArchiveIntermediates/FetchMeeBySwiftUI/IntermediateBuildFilesPath/Swifter.build/Release-iphoneos/SwifteriOS.build/Objects-normal/armv7/SwifteriOS.swiftmodule -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/jyrnan/Library/Developer/Xcode/DerivedData/FetchMeeBySwiftUI-dqsbshiaztjeorgjkelrhfgkzkes/Build/Intermediates.noindex/ArchiveIntermediates/FetchMeeBySwiftUI/IntermediateBuildFilesPath/Swifter.build/Release-iphoneos/SwifteriOS.build/Objects-normal/armv7/SwifteriOS_dependency_info.dat -o /Users/jyrnan/Library/Developer/Xcode/DerivedData/FetchMeeBySwiftUI-dqsbshiaztjeorgjkelrhfgkzkes/Build/Intermediates.noindex/ArchiveIntermediates/FetchMeeBySwiftUI/IntermediateBuildFilesPath/Swifter.build/Release-iphoneos/SwifteriOS.build/Objects-normal/armv7/Binary/SwifteriOS

Undefined symbols for architecture armv7:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in URL++.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

**Comment by jyrnan** [comment]
it works, I don't know why :(

**Comment by kichiemon** [comment]
I face the same problem on Xcode12 beta 4.

> Undefined symbols for architecture armv7:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in URL++.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kichiemon** [comment]
This archive error is Fixed on Xcode12 beta 6.
