### ISSUE TITLE
FailureHandler doesn't return anything useful

### ISSUE THREAD

**Issue by halpz** [mattdonnelly/Swifter#312]
When I get a failure upon a search, for example a 404,  how do I determine the cause of failure?

I would like to know whether a search has 404'd or if it has failed because an auth token has expired for example

**Comment by halpz** [comment]
is there a way to check that 

```
self.swifter = Swifter(consumerKey: consumerKey,
                               consumerSecret: consumerSecret,
                               oauthToken: key,
                               oauthTokenSecret: secret)
```

has successfully logged in?

**Comment by meteochu** [comment]
You should be getting specific response codes and error codes depending on the type of error. In the failure handler, you get a response with type `Error`. If you cast it to a `SwifterError` type, you should be able to get more information of the type of error that occurred. 

For the case of finding an invalid token, you could check the case of `SwifterError.urlResponseError(status, headers, errorCode)` where errorCode would correspond with the defined list of errors on the [Twitter Developer Forum](https://developer.twitter.com/en/docs/basics/response-codes)

**Comment by halpz** [comment]
thanks!
