### ISSUE TITLE
Authentification callback completion block not called

### ISSUE THREAD

**Issue by jerometonnelier** [mattdonnelly/Swifter#320]
Hi,

I'm sorry if I post a dumb question, but I configured my Twitter App on the Twitter Website, use a callback URL. After login, the webpage re-opens my app using the callback URL, but never using the success completion block from the authorize(withCallback: ...) method. 
Am I doing something wrong? How am I supposed to get the completion state when using a callback URL call?

Thanks a lot for your support.

**Comment by meteochu** [comment]
Look at the example project in the AppDelegate, you need to alert Swifter that the callback was fired.
```
Swifter.handleOpenURL(url, callbackURL: callbackUrl)
```

**Comment by jerometonnelier** [comment]
My bad. I was looking for documentation, I did not thought of searching for an example app.
Thanks a lot ;-)

**Comment by jerometonnelier** [comment]
@meteochu  Quick follow-up question though : I can login, but it does not seem persistent. Each time I relaunch the app (simulator), I have to re-log (I did not use the forceLogin option). Can you help me with that too? Thanks.

**Comment by meteochu** [comment]
The login/authorize method should only be called to retrieve an OAuth token from Twitter. It is up to you to persist that yourself, and use it to create a Swifter object afterwards. Since it is an OAuth token (and secret), it is recommended that you persist this data in the user's keychain.

**Comment by jerometonnelier** [comment]
Ah ok. Thanks a lot for your help ;-)
