### ISSUE TITLE
library swiftyJSON error after import swifter in viewcontroller

### ISSUE THREAD

**Issue by stnwj** [mattdonnelly/Swifter#338]
<img width="754" alt="gambar" src="https://user-images.githubusercontent.com/43704613/102738763-af8a9500-437d-11eb-9ee1-911278f3dc4b.png">
after import swifter. my JSON error.
I tried delete import swifter. my JSON back to normal

I think you can change your class JSON
<img width="233" alt="Screen Shot 2020-12-21 at 11 24 30" src="https://user-images.githubusercontent.com/43704613/102739244-2b391180-437f-11eb-8cea-efb6223fc489.png">

**Comment by meteochu** [comment]
I am pretty sure this is due to the fact that SwiftyJSON also defines their own JSON class. You just have to refer to them based on Module name. i.e. `SwiftyJSON.JSON` or `Swifter.JSON`

You can also just do a global typealias if you prefer one over the other by doing:
```swift
typealias JSON = Swifter.JSON // or SwiftyJSON.JSON
```
