### ISSUE TITLE
Integer overflow in 32bit environment

### ISSUE THREAD

**Issue by gecko655** [mattdonnelly/Swifter#43]
Twitter's status id is now more than 2^32, so we cannot deal with the status id as Int with 32bit environment (such as iPhone4S).

For example, the code doesn't work correctly with iPhone4S, due to integer overflow.

``` swift
let a:Int = 515496848048390145
print(a) //prints -289275903 
```

Therefore, I can't use `func getStatusesShowWithID(id: Int, ...)` to show https://twitter.com/gecko655/status/515496848048390145.

I think Swifter should include the same method with String argument, like 
`func getStatusesShowWithID(id: String, ...)`,
or should change the method to `func getStatusesShowWithID(id: Int64, ...)`.

Is it correct?

**Comment by nilswiersema** [comment]
Same problem in issue #70.

The use of the architecture-flavored `Swift.Int` for cursors renders them practically unusable on 32-bit platforms, as your app will choke on an overflow error when trying to parse a 64-bit cursor as a 32-bit integer.

Replacing the integers by either strings or Int64 ('long long') fixes the problem.
