### ISSUE TITLE
Release settings?

### ISSUE THREAD

**Issue by benlachman** [mattdonnelly/Swifter#48]
Have you considered adding some documentation on using Swifter in shipping products? I just attempted to build a project including Swifter for an Ad Hoc build and it failed. I'd prefer not to change the project settings for the framework, but am unclear if that will be necessary to get the project to build ad hoc or not.

**Comment by alexdd55** [comment]
Same here. :(

**Comment by zntfdr** [comment]
Outdated discussion.
