### ISSUE TITLE
Unresolved identifiers when building 6.1 branch

### ISSUE THREAD

**Issue by loh** [mattdonnelly/Swifter#55]
I get the following Swift Compiler Errors when building in Xcode 6.1 with the Swifter 6.1 branch:

Use of unresolved identifier 'CC_SHA1_DIGEST_LENGTH'
Use of unresolved identifier 'CCHmac'
Use of unresolved identifier 'CCHmacAlgorithm'
Use of unresolved identifier 'kCCHmacAlgSHA1'

I added Swifter to my project by dragging the Swifter.xcodeproj file and Swifter directory (but not the Mac and iOS demo projects) into Xcode. I also added SwifteriOS.framework to the Link Binary With Libraries section under Build Phases.

**Comment by MdBee** [comment]
I also ran into these errors.  They went away when I removed the Swifter folder from my project and just used the SwifteriOS.framework.

**Comment by ZaidPathan** [comment]
There are two ways to solve this,
1.If you have Bridging-Header.h already setup in your project.
2.If you don't have Bridging-Header.h already setup in your project.


1.If you have Bridging-Header.h already setup in your project.

-Open you Bridging-Header.h file.
-Write this,

#import "Swifter-Bridging-Header.h"

2.If you don't have Bridging-Header.h already setup in your project.

In Build Settings for your app target, search for "Objective-C Bridging Header" and set it to the path to Swifter-Bridging-Header.h

(-by matt)

That's it.
