### ISSUE TITLE
Integrating Swifter into Objective C 

### ISSUE THREAD

**Issue by janicetaylor** [mattdonnelly/Swifter#61]
Has anyone tried to integrate this framework into an objective C project? 

I had to make the Swifter class inherit from NSObject (so the objective C side could see it), and even then it's giving me an issue when I try to init the object -- 

no visible interface for 'Swifter' declares the selector initWithConsumerKey 

I checked the SwifteriOS-Swift.h (created by the compiler) and it seems correct. 

I also have the following in my .h file:

#import < SwifteriOS/SwifteriOS-Swift.h >

@import SwifteriOS;
@class Swifter;

**Comment by chiragpurohit71085** [comment]
Hi 

Anybody has any luck with this?

I have tried as following , but no success... 

#import "target-Swift.h"    
@import SwifteriOS;
@class Swifter;
