### ISSUE TITLE
Tweeting with media - suggestion

### ISSUE THREAD

**Issue by Jem72** [mattdonnelly/Swifter#62]
I've recently added the following extension to my own copy of Swifter - I couldn't find anything else that did this, but this supports the new media uploads functionality for twitter and allows me to parse out the media ID so as to be able to tweet with an image.

public extension Swifter {
    public func postMediaFile(media: NSData, success: ((status: Dictionary<String, JSONValue>?) -> Void)?, failure: FailureHandler?) {
        var path: String = "media/upload.json"

        var parameters = Dictionary<String, AnyObject>()
        parameters["media"] = media
        parameters[Swifter.DataParameters.dataKey] = "media"
        self.postJSONWithPath(path, baseURL: self.uploadURL, parameters: parameters, uploadProgress: nil, downloadProgress: nil, success: {
            json, response in

            success?(status: json.object)
            return

            }, failure: failure)
    }
}

**Comment by zntfdr** [comment]
Added support by @s-aska, see https://github.com/mattdonnelly/Swifter/commit/07f2c765316d4acac3e58460afd00221a3bc635e .
