### ISSUE TITLE
[ASK] How do I save the session?

### ISSUE THREAD

**Issue by iRILLLL** [mattdonnelly/Swifter#71]
I'm sorry if this is a stupid question, but I'm just learned about OAuth. 

I'm using your library for my school's project.

how do I save the login session? so I don't need to relogin everytime I opened my application?

thank you very much and sorry for my bad English.

**Comment by s-aska** [comment]
# Access token
```swift

// save session
let accessToken = swifter.client.credential.accessToken {
	let key = accessToken.key // String
	let secret = accessToken.secret // String
	// save the key and secret to Keychain
}

// load session
let key = ... // load the key from Keychain
let secret = ... // load the secret from Keychain
let accessToken = SwifterCredential.OAuthAccessToken(key: key, secret: secret)
let credential = SwifterCredential(accessToken: accessToken)

let swifter = Swifter(consumerKey: "", consumerSecret: "")
swifter.client.credential = credential
```

# ACAccount
```swift

// save session
if let account = swifter.client.credential.account {
	let identifier = account.identifier // String
	// save identifier to Keychain
}

// load session
let identifier = ... // load the identifier by Keychain
let account = ACAccountStore().accountWithIdentifier(identifier)
let credential = SwifterCredential(account: account)

let swifter = Swifter(consumerKey: "", consumerSecret: "")
swifter.client.credential = credential
```

**Comment by iRILLLL** [comment]
Hi, thanks for your time to answer my question.

I've got an error when I tried to load the session

HTTP Status 400: Bad Request, Response: {"errors":[{"message":"Bad Authentication data","code":215}]}

if I change the codes when I load the session to this 

let swifter = Swifter(consumerKey: myConsumerKey, consumerSecret: myConsumerSecret)
swifter.client.credential = credential

I got this error

HTTP Status 401: Unauthorized, Response: {"errors":[{"message":"Could not authenticate you","code":32}]}


do you know where is the problem?

**Comment by s-aska** [comment]
umm.
there is a possibility that you tweet without setting the write permissions.

https://apps.twitter.com/app/YOUR_APP_ID/permissions

Note: https://dev.twitter.com/overview/api/response-codes

**Comment by jchesne** [comment]
Hello s-aska, 

I have tried to update twitter session with your code, here is mine : 
```
        let key = "my-twitter-from-keychain"
        let secret = "my-twitter-secret-from-keychain"
        let accessToken = SwifterCredential.OAuthAccessToken(key: key!, secret: secret!)
        let credential = SwifterCredential(accessToken: accessToken)
        
         self.swifter = Swifter(consumerKey: "my-key", consumerSecret: "my-secret")
        swifter.client.credential = credential
```
But this seem not working properly, like if not call to twitter were done. 
Here is my credential : 

![swifter-help](https://cloud.githubusercontent.com/assets/1859737/6167306/3833cfda-b2ba-11e4-917a-8f28ce1407ea.png)

As you can see, data are nil, can you tell me have i don't do properly please ?

Thanks,

**Comment by alexdd55** [comment]
i did this to solve this problem:
```
self.swifter.authorizeWithCallbackURL(NSURL(string: "com.snowfinch://success")!, success: {
	credential, response in
		var tmp = self.swifter.client.credential?.accessToken?
		self.saveUserToken(tmp!)
				
},failure: failureHandler
)

func saveUserToken(data: SwifterCredential.OAuthAccessToken) -> Bool {
		
		var userdata = NSUserDefaults.standardUserDefaults()
		userdata.setObject(data.key, forKey: "key")
		userdata.setObject(data.secret, forKey: "secret")
		userdata.setObject(data.screenName, forKey: "screenName")
		userdata.setObject(data.userID, forKey: "userID")
		userdata.setObject(data.verifier, forKey: "verifier")
		userdata.synchronize()
		
		return true
	}

```

i am sure, there are better ways to do that ;)

**Comment by jchesne** [comment]
Hi Alex,

My question was not about how to save usertoken.

My problem is when i restart my app, how do i ask to twitter/swifter to refresh the token with my saved usertoken for dont have to login again anymore ?

Do you succeed to do this ?

**Comment by alexdd55** [comment]
i updated my answer above.

after authentication (twitter webpage) there is now need to login again, until you uninstall the app from your phone or simulator

**Comment by jchesne** [comment]
Ok Alex, and can you confirm that when you debug the user variable at this line : 
user = self.userHelper.fetchUserQData()
You fetch exactly the same data as authorizeWithCallbackURL do please with your tmp var ?

As you can see in my debug picture, only the key and secret have data,

**Comment by alexdd55** [comment]
i had to add another piece of code.  ;)

actually, you could just copy and paste the code. it will do a couple of steps to get the data and save it for all coming requests, incl authentication call if neccessary.

**Comment by jchesne** [comment]
Thanks for your code ;)

So you confirm that : 
```
var access = SwifterCredential.OAuthAccessToken(key: tkey , secret: tsecret)
return SwifterCredential(accessToken: access)
```
Does'nt return the fully object whith screenName and userID ? Its not normal isn't it ?

**Comment by alexdd55** [comment]
i do not really know if its normal - to be honest i expected this data, too ;) - but during debugging it shows, i need to do a request to get it....

**Comment by jchesne** [comment]
Ok, i will continu to investigate. Thanks for you help !

**Comment by zntfdr** [comment]
It's been over an year since the last update of this issue: I believe the school's project is done by now :)
