### ISSUE TITLE
[ASK] Is there any way to Login with Installed Twitter app.?

### ISSUE THREAD

**Issue by ZaidPathan** [mattdonnelly/Swifter#75]
let swifter = Swifter(consumerKey: TWITTER_CONSUMER_KEY, consumerSecret: TWITTER_CONSUMER_SECRET,appOnly: true)

this does not worked for me.

I Wants to login user from Twitter app as well as Authentication from browser.

From browser it's working.

But it is not redirecting to Twitter app.

**Comment by alexdd55** [comment]
did you link to your bundle-identifier?

**Comment by ZaidPathan** [comment]
No, how can I do that.?

**Comment by alexdd55** [comment]
´´´
 self.swifter.authorizeWithCallbackURL(NSURL(string: "com.YOUR_APP://success")!, success: {
´´´
actually very easy, but took me also a long time to find out ;)

**Comment by ZaidPathan** [comment]
Unfortunately, I did that too...but it didn't help...

**Comment by alexdd55** [comment]
the callback url need to be your app and i guess you already have add the openurl stuff in your appdelegate?

**Comment by ZaidPathan** [comment]
Right,so shouldn't I use that in appdelegate?

**Comment by alexdd55** [comment]
thats fine.and the callback is your Bundle Identifier?
its is like
LTD.DOMAIN.APPNAME
and i put
LTD.DOMAIN://success
as callback.

**Comment by ZaidPathan** [comment]
No, I used myapp://success

**Comment by ZaidPathan** [comment]
So,LTD.DOMAIN://success will help me in login with Twitter app.?

**Comment by alexdd55** [comment]
yes, works for me,
i just recognized you want "appOnly" authentication.
i can not confirm it works the same way, because you need the bearer token and this might be handled slightly different?!
check out this link: https://dev.twitter.com/oauth/application-only

**Comment by MHaroonBaig** [comment]
@ZaidPathan yes it is possible only if the user has configured his Twitter account in the Settings. You can then fetch his credentials from there and authenticate the user. @alexdd55 I've used the method here https://github.com/MHaroonBaig/Swift-Beautify in my sample application. The file is located here https://github.com/MHaroonBaig/Swift-Beautify/blob/master/Picker/DoneViewController.swift

**Comment by ZaidPathan** [comment]
Thanks Haroon bro,
I appreciate your and Alex's valuable response.
so is it not possible to fetch user data from installed app.(not settings account).?

**Comment by MHaroonBaig** [comment]
No. The only possibility is when the user has configured his official Twitter account in the settings. You can do a work around. Like, many people don't know about configuring their accounts in the Settings section. What you can do is that, you can apply the check and fetch the credentials through the ACAccountStore. Then incase of any error, redirect the user to the settings screen manually so that they could enter their credentials there. You can then authenticate them using the credentials that they would enter.

**Comment by ZaidPathan** [comment]
Alright,
So, I'm closing this issue.
Thanks.
