### ISSUE TITLE
SwifterHTTPRequest : Ambiguous use of 'filter'

### ISSUE THREAD

**Issue by Kiran-Patel** [mattdonnelly/Swifter#76]
Compile Error: SwifterHTTPRequest.swift:118:43: Ambiguous use of 'filter'
Result: Not able to run my xCode project

File name : "Swifter/SwifterHTTPRequest.swift"

Code which cause for the error:
 public func start() {
.   
.   some lines of code
.   
var nonOAuthParameters = self.parameters.filter { key, _ in !key.hasPrefix("oauth_") }
.   
.   some lines of code
.   
}

Is there any solution available for same?

**Comment by zntfdr** [comment]
Outdated Swift language-related problem.

The right code was probably something like:
`self.parameters.filter({$0.hasPrefix("oauth_")})`
