### ISSUE TITLE
callback isnt coming.

### ISSUE THREAD

**Issue by hiteshjoshi** [mattdonnelly/Swifter#80]
The code below can autorize on safari browser quite well. But the callback isn't happening.

    println("NO ACCOUNTS! Trying to takeit for the website.")
    self.swifter.authorizeWithCallbackURL(NSURL(string:"com.ttagit://success")!, success: { (accessToken: SwifterCredential.OAuthAccessToken?, response: NSURLResponse) -> Void in
    
    println(accessToken)
    var tmp = self.swifter.client.credential?.accessToken?
    self.userHelper.saveUserToken(tmp!)
    var user = self.userHelper.fetchUserQData()
    self.fetchTwitterHomeStream(user)
    }, failure: failureHandler)

Any suggestions?

**Comment by hiteshjoshi** [comment]
After debugging, it feels like this function is not getting executed.

    NSNotificationCenter.defaultCenter().addObserverForName(CallbackNotification.notificationName, object: nil, queue: NSOperationQueue.mainQueue(), usingBlock:{
                notification in

And since, this is the only way to call the success callback function, the callback never happens.

Any basic xcode configuration I am missing? Any help is appreciated

**Comment by hiteshjoshi** [comment]
Figured it out! Its AppDelegate. I forgot to assign swifter url.

**Comment by joshwolff1** [comment]
For reference, hiteshjoshi is referring to the function this SO user used in his AppDelegate:

https://stackoverflow.com/questions/28005919/how-to-authorize-twitter-with-swifter
