### ISSUE TITLE
How to save the [JSONValue] into NSUserDefaults?

### ISSUE THREAD

**Issue by VasuLaroiya** [mattdonnelly/Swifter#82]

**Comment by alexdd55** [comment]
i might be wrong, but as far as i know, this is not possible, because NSUserDefaults can not take this type.

**Comment by VasuLaroiya** [comment]
Is there any way to save the data at all?

**Comment by alexdd55** [comment]
depends. in NSUserDefault, i would stote user credentials.
for a bigger amount of data i use [realm.io](http://realm.io). its very easy to use and fast.

**Comment by VasuLaroiya** [comment]
i tried realm.io but it would let me save the [JSONValue] result i get

**Comment by mattdonnelly** [comment]
The JSON class isn't really designed to be persisted. It's main purpose is to make it easier for you to access elements within the data returned by Twitter. But if you'd like to persist this data I'd suggest writing classes to represent the information you'd like to store and using something like core data to store them.

I might add an easier way to do this in the future, but don't have time right now

**Comment by zntfdr** [comment]
Answered.
