### ISSUE TITLE
[Endpoint typo] 'users/search/json' should be 'users/search.json'

### ISSUE THREAD

**Issue by romaincointepas** [mattdonnelly/Swifter#85]
https://github.com/mattdonnelly/Swifter/blob/master/Swifter/SwifterUsers.swift#L541

Probably a typo.

Doc: https://dev.twitter.com/rest/reference/get/users/search

**Comment by alexdd55** [comment]
added pull request https://github.com/mattdonnelly/Swifter/pull/91
