### ISSUE TITLE
Parameters are not passed in getTrendsPlaceWithWOEID

### ISSUE THREAD

**Issue by laplace** [mattdonnelly/Swifter#86]
When executing getTrendsPlaceWithWOEID I keep receiving page not found, tracing the issue I found that the parameters are not passed to the actual execution procedure.

Solution: 

self.getJSONWithPath(path, baseURL: self.apiURL, parameters: [:], uploadProgress: nil, downloadProgress: nil, success:{

replace it with

self.getJSONWithPath(path, baseURL: self.apiURL, parameters: parameters, uploadProgress: nil, downloadProgress: nil, success:{

**Comment by alexdd55** [comment]
added a pull request
https://github.com/mattdonnelly/Swifter/pull/91
