### ISSUE TITLE
Help with Stream JSON parsing

### ISSUE THREAD

**Issue by mbodge** [mattdonnelly/Swifter#93]
Sorry for the newbie question, but I'm hung up on how to parse the JSON in this example. Everything i've tried has failed me...any documentation or example code would be super helpful and appreciative.

m

```
swifter.getStatusesSampleDelimited(progress: {
    (status: Dictionary<String, JSONValue>?) in

   // HELP!!!!!!

    }, stallWarnings: {
        (code: String?, message: String?, percentFull: Int?) in
    }, failure: {
        (error: NSError) in
    })
```

**Comment by gecko655** [comment]
If you use only the content of tweets, you can see the tweets by
```swift
println(status?["text"]?.string) //-> Text of the tweet
println(status?["created_at"].string) //->  Creation time of the tweet
```
The status can be not only the content of tweets but the notifications to the users
(See https://dev.twitter.com/streaming/overview/messages-types#public_stream_messages )
So, you should branch the control flow by the type of the status.

```swift
if status?["id_str"]?.string != nil {
  println(status?["text"]?.string) //-> Text of the tweet
  println(status?["created_at"].string) //->  Creation time of the tweet
} else if status?["delete"]?.string != nil {
  ...
}
```

**Comment by mbodge** [comment]
Thank you so much.
