### ISSUE TITLE
Authorization problem

### ISSUE THREAD

**Issue by Bogunov** [mattdonnelly/Swifter#95]
I try to authorize to twitter with swifter, but i don't know how to do it with web-link, i get link by api - http://xxxxxx.com/oauth/twitter-connect?register_token=twitter_55096a373db50, in browser it works fine, but how put it in login procedure of swifter? i need to change callback url?

1) First i put  keys in swifter:

 self.swifter = Swifter(consumerKey: "qAEuhp1FPXtOKAFxewLWg", consumerSecret: "w0uBFtqjHWbiI7odT81MN4K6ZccFayerpzZxXOg")

2) Than try to login:
swifter.authorizeWithCallbackURL(NSURL(string: "swifter://success")!, success: {
                (accessToken: SwifterCredential.OAuthAccessToken?, response: NSURLResponse) in
//save tokens in app
            self.accessTokenKey = accessToken?.key
            self.accessTokenSecret = accessToken!.secret
            self.save()        
        },
            failure: { (error) -> Void in
                NSLog("error: \(error)")
        })
    }

**Comment by alexdd55** [comment]
First of all: do not post your keys here. ;)

for the login: replace "swifter://success" with "YOUR_APP_NAME://sucess"
this should solve the problem

**Comment by Bogunov** [comment]
this is not real keys, just example. 
try to add app name and get error:
error: Error Domain=NSURLErrorDomain Code=401 "HTTP Status 401: Unauthorized, Response: <?xml version="1.0" encoding="UTF-8"?>

  <error>Desktop applications only support the oauth_callback value 'oob'</error>

**Comment by alexdd55** [comment]
oh, you are on adesktopapp? sorry,didn't know.
i just work on ios,

**Comment by Bogunov** [comment]
no its ios, if i want to use (register_token) how i should add it in swifter.authorizeWithCallbackURL? in call backURL just put name of app in twitter, nothing more?

**Comment by alexdd55** [comment]
i did this:
```
oauthswift.authorizeWithCallbackURL(NSURL(string: "YOUR_DOMAIN.YOUR_APP_NAME://success")!, success: {
			credential, response, responseString in
			println(credential)
}, failure: failureHandler)
```

**Comment by Bogunov** [comment]
Trying to put AccessToken inside(still don't work) :

        self.swifter = Swifter(consumerKey: "************", consumerSecret: "*********")
        let accessToken = SwifterCredential.OAuthAccessToken(queryString: "twitter_*********")???
        let credential = SwifterCredential(accessToken: accessToken)
        swifter.client.credential = credential

**Comment by alexdd55** [comment]
```let accessToken = SwifterCredential.OAuthAccessToken(key: twitterkey , secret: twittersecret)```

**Comment by Bogunov** [comment]
i dont have this keys, i have authorize_url, is a possibility to connect directly to authorize_url?

**Comment by alexdd55** [comment]
you get those from twitter, when you register a new app in their dev center

**Comment by alexdd55** [comment]
oauthswift.authorizeWithCallbackURL
