### ISSUE TITLE
How to create an ACAccount?

### ISSUE THREAD

**Issue by codecowboy** [mattdonnelly/Swifter#98]
The docs state that I should be able to instantiate Swifter with an ACAccount but how to I create that account?

```

import UIKit
import SwifteriOS

twitterAccount = "@twitterhandle" // how should this be created?

let swifter = Swifter(account: twitterAccount)

swifter.getStatusesHomeTimeLineWithCount(20, success: {
    (statuses: JSONValue[]?) in
    
    print(statuses)
    
  }, failure: {
    (error: NSError) in
    
    // ...
    
})

```

I was just trying this in an XCode playground. Can I just do a call like that to a timeline or do I need to go through OAuth setup first? I've added the SwifteriOS framework to the Workspace.

**UPDATE**
It looks like ACAccount is an Apple API and that I would only use that if I had an accountstore locally, correct?

**Comment by mattdonnelly** [comment]
Take a look at Apple's docs or the demo projects in the repo for an example of how to create an instance of ACAccount

**Comment by codecowboy** [comment]
The account store is where Apple maintains user credentials e.g. Facebook, Twitter on the device (accessible via settings). In the context of an XCode playground for creating a quick test, this is not the best approach.
